default-lease-time 600;
max-lease-time 7200;
authoritative;
log-facility local7;

subnet 172.28.0.0 netmask 255.255.255.0 {
  range 172.28.0.100 172.28.0.200;
  option routers 172.28.0.13;
  option domain-name-servers 172.28.0.12;
  option domain-name "corp.local";
}
