#!/usr/bin/env python3
"""Generate Watchtower UEBA simulation test scenarios."""

from pathlib import Path

# (name, category, role, olay, neden_supheli, sapma, severity, gerceklik)
SCENARIOS: list[tuple[str, ...]] = [
    ("Gece Yedek Çekimi", "veri sızdırma", "Muhasebe",
     "Muhasebe çalışanı normalde gündüz 200-400 MB finans sunucusundan rapor çekerken Cuma 23:47'de aynı sunucudan 18.4 GB toplu dosya indiriyor; arşiv (.zip) ve CSV paketleri.",
     "Rol için olağandışı saat, tek oturumda 45x veri hacmi, arşiv formatı toplu dışa aktarım paterni.",
     "Günlük ort. 320 MB → 18.4 GB; saat 09-18 dışı ilk kez.", "CRITICAL",
     "İşten ayrılma öncesi veya rakibe veri taşıma girişimlerinde sık görülür."),
    ("USB Toplu Kopya", "veri sızdırma", "Satış",
     "Satış temsilcisi CRM sunucusundan 2.1 GB veriyi 14 dakikada USB'ye kopyalıyor.",
     "Satışta USB yasak; CRM toplu okuma + USB yazma korelasyonu.",
     "USB: ayda 0-1 → 2.1 GB tek sefer.", "ALERT", "Fuar öncesi offline sunum."),
    ("Payroll Dump", "veri sızdırma", "İK",
     "İK uzmanı payroll-db'den tüm maaş tablosunu 890 MB SQL export ile indiriyor.",
     "Tam tablo export; normal iş akışı tek çalışan sorgusu.",
     "Ort. 2-5 MB → 890 MB.", "CRITICAL", "Maaş bilgisi sızdırma/şantaj."),
    ("Kaynak Kod Arşivi", "veri sızdırma", "Yazılım Geliştirici",
     "Geliştirici git-mirror'dan 4.7 GB tüm repo ağacı çekiyor; projesi tek microservice.",
     "Yetkili repo dışı tüm branch çekimi; hafta sonu.",
     "150 MB/hafta → 4.7 GB; repo 1→47.", "ALERT", "Ayrılış öncesi IP biriktirme."),
    ("Hukuk Dava Arşivi", "veri sızdırma", "Hukuk",
     "Hukuk danışmanı dava-arsiv'ten 120 PDF'i ZIP ile 3.2 GB indiriyor.",
     "Toplu indirme; müşteri kodlu dosya adları.",
     "5-10 dosya/gün → 120 dosya.", "WARNING", "Mahkeme hazırlığı meşru olabilir."),
    ("BI Ham PII Export", "veri sızdırma", "Veri Analisti",
     "Analist DWH'den ham müşteri PII ile 12 GB parquet export alıyor.",
     "Dashboard sorgusu 50-200 MB; ham PII export nadir.",
     "12 GB vs ort. 180 MB.", "ALERT", "Yanlış tüm veri seçimi."),
    ("Stajyer CRM Export", "veri sızdırma", "Stajyer",
     "Stajyer 2. haftada CRM'den 45.000 satır müşteri kaydını Excel'e aktarıyor (220 MB).",
     "Stajyer yetkisi demo ortamı; prod export yok.",
     "İlk CRM export; 9x satır üst sınır.", "CRITICAL", "Görev yanlış anlaşılması."),
    ("CFO USB Kopya", "veri sızdırma", "CFO",
     "CFO bütçe sunucusundan 1.8 GB indirip ardından USB'ye kopyalıyor.",
     "İndirme meşru; USB CFO baseline'ında yılda 0.",
     "USB olayı: 0 → 1.8 GB.", "WARNING", "YK sunumu + politika ihlali."),
    ("Destek Ticket PII", "veri sızdırma", "Destek Personeli",
     "Destek attachment store'dan 800 ticket ekini 6.1 GB zip'liyor.",
     "Kimlik fotokopisi ve ekran görüntüsü içerebilir.",
     "50 MB/gün → 6.1 GB.", "ALERT", "Yedekleme bahanesi."),
    ("Admin Yanlış VM", "veri sızdırma", "IT Admin",
     "Admin prod-HR VM snapshot'ını workstation'a 90 GB çekiyor.",
     "Hedef workstation; backup job dışı saat.",
     "Tek sefer 90 GB.", "CRITICAL", "Operasyon hatası."),
    # --- credential ihlali ---
    ("LDAP Bulk Bind", "credential ihlali", "Güvenlik Görevlisi",
     "SOC analisti prod ldap-replica'ya test bind ile 12.000 auth/dk üretiyor.",
     "Test prod'da; rate limit aşımı.", "50 → 12.000 auth/dk", "WARNING", "Pen test unutulmuş."),
    ("Deploy Key 3 IP", "credential ihlali", "Yazılım Geliştirici",
     "svc-deploy API key 3 farklı workstation IP'den kullanılıyor.",
     "Key tek makineye bağlı olmalı.", "Kaynak IP: 1 → 3", "ALERT", "Slack'te key paylaşımı."),
    ("Stajyer Çift Oturum", "credential ihlali", "Stajyer",
     "Stajyer hesabı aynı anda 2 workstation'da aktif; biri mentor masası değil.",
     "Hesap paylaşımı.", "Eşzamanlı oturum: 2 host", "ALERT", "Mentor şifre vermiş."),
    ("CEO Asistan İK", "credential ihlali", "CEO",
     "CEO hesabı İK sunucusuna erişiyor; session fingerprint asistan PC.",
     "İmpersonation riski.", "CEO→İK: yılda 0", "WARNING", "Asistan devri."),
    ("Gece Admin TGT", "credential ihlali", "IT Admin",
     "Admin hesabından 02:00'de 8 sunucuya ardışık Kerberos TGT.",
     "Lateral movement işareti.", "Gece TGT: 0 → 8", "CRITICAL", "PtH sonrası."),
    ("Jira Key Bulk", "credential ihlali", "Proje Yöneticisi",
     "Read-only Jira key ile gece 40.000 issue API çağrısı.",
     "Read-only ile bulk export.", "200/gün → 40.000", "ALERT", "Rapor scripti."),
    ("Paylaşılan RDP", "credential ihlali", "Muhasebe",
     "Muhasebe kullanıcısı başka departman PC'sine RDP; kendi şifresiyle ikinci oturum.",
     "Credential sharing.", "RDP hedef: 0 → 3 farklı host/hafta", "WARNING", "Acil fatura onayı."),
    ("Token Vault Dump", "credential ihlali", "IT Admin",
     "Admin iç HashiCorp Vault audit'te 200 secret read; bakım penceresi dışı.",
     "Secret enumeration.", "Vault read: 5/gün → 200", "CRITICAL", "Compromise veya kötü niyet."),
    ("Stajyer Mentor ADUC", "credential ihlali", "Stajyer",
     "Stajyer RDP ile mentor PC'den ADUC açıyor.",
     "Paylaşılan credential.", "RDP mentor: 0", "ALERT", "Eğitim kötü uygulama."),
    ("CFO Asistan Mail", "credential ihlali", "CFO",
     "CFO mailbox'tan toplu mail silme; client IP asistan subnet.",
     "Yetki devri ihlali.", "Toplu silme: 0", "WARNING", "Temizlik talebi."),
    # --- yetkisiz erişim ---
    ("Satış ERP Erişim", "yetkisiz erişim", "Satış",
     "Satış rep finans-erp'ye RDP; fatura modülü açık.", "Satış grubunda ERP yok.",
     "İlk ERP erişim", "ALERT", "Komisyon araştırması."),
    ("Junior Prod DB", "yetkisiz erişim", "Yazılım Geliştirici",
     "Junior dev prod-db-01 SSMS SELECT *.", "Prod sadece DBA.", "Prod: 0", "CRITICAL", "Bug fix bahanesi."),
    ("Hukuk Performans", "yetkisiz erişim", "Hukuk",
     "Hukuk performans-değerlendirme share'ine erişiyor.", "Dava dışı HR.", "İlk erişim", "WARNING", "İş davası."),
    ("Muhasebe DA Deneme", "yetkisiz erişim", "Muhasebe",
     "Domain Admin grubuna ekleme denemesi başarısız.", "Privilege escalation.", "AD write: 0", "CRITICAL", "Phishing sonrası."),
    ("PM SIEM Konsol", "yetkisiz erişim", "Proje Yöneticisi",
     "PM SIEM web konsoluna login.", "SOC rolü yok.", "İlk SIEM", "ALERT", "Proje inceleme."),
    ("Stajyer Get-ADUser", "yetkisiz erişim", "Stajyer",
     "PowerShell Get-ADUser -Filter *.", "AD okuma yok.", "Cmdlet: 0", "ALERT", "Tutorial."),
    ("CFO Git Gezinme", "yetkisiz erişim", "CFO",
     "CFO git-internal'da repo listesi geziyor.", "C-level kod erişimi yok.", "İlk git", "LOG", "Yanlış link."),
    ("Destek DC RDP", "yetkisiz erişim", "Destek Personeli",
     "Şifre reset için DC'ye RDP.", "DC sadece IT Admin.", "DC RDP: 0", "CRITICAL", "Yanlış prosedür."),
    ("Veri Analisti Prod", "yetkisiz erişim", "Veri Analisti",
     "Analist prod-ml-feature store'a write.", "Prod write yasak.", "Write: 0", "ALERT", "Model güncelleme."),
    ("İK Finans Modül", "yetkisiz erişim", "İK",
     "İK çalışanı finans onay modülünde bekleyen ödemeleri görüntülüyor.", "Çapraz yetki yok.",
     "Finans modül: 0", "WARNING", "Bordro uyumsuzluğu araştırması."),
    ("CTO HR Backup", "yetkisiz erişim", "CTO",
     "CTO hr-backup share'ine yazma denemesi.", "CTO HR write yok.", "Write deneme", "LOG", "Yanlış klasör."),
    # --- insider threat ---
    ("Ayrılış Ramp", "insider threat", "Yazılım Geliştirici",
     "İstifadan 5 gün önce günlük çekim 200 MB→3 GB.", "Offboarding pattern.",
     "5 gün artış", "ALERT", "Klasik insider."),
    ("İK Disiplin Tarama", "insider threat", "İK",
     "İK 12 çalışanın disiplin kaydına bakıyor.", "Need-to-know.", "12 profil", "WARNING", "Dedikodu."),
    ("Satış Segment Model", "insider threat", "Satış",
     "Ayrılan rep müşteri segmentasyon modeline 3 gün erişiyor.", "Rakip verisi.", "Model+ayrılış", "ALERT", "Headhunter."),
    ("Shadow Admin", "insider threat", "IT Admin",
     "Yeni local admin svc_monitor; change ticket yok.", "Shadow account.", "Yeni hesap", "CRITICAL", "Kalıcı erişim."),
    ("Sahte Tedarikçi IBAN", "insider threat", "Muhasebe",
     "Tedarikçi master'da onaysız IBAN değişikliği.", "Fraud.", "Onaysız write", "CRITICAL", "Vendor fraud."),
    ("SOC Log Suppress", "insider threat", "Güvenlik Görevlisi",
     "SOC kendi host için SIEM suppress rule ekliyor.", "Anti-forensics.", "Self suppress", "CRITICAL", "Kendi ihlali."),
    ("PM Maliyet Gizleme", "insider threat", "Proje Yöneticisi",
     "Proje maliyet tablosunda 50 hücre toplu güncelleme.", "Yetkisiz finans write.", "50x write", "ALERT", "Bütçe manipülasyon."),
    ("ML Model Hırsızlık", "insider threat", "Veri Analisti",
     "ML artifact 2.3 GB indirme; export policy ihlal.", "IP hırsızlığı.", "Export: 0", "ALERT", "Yan iş."),
    ("CEO Asistan Strateji", "insider threat", "CEO",
     "Asistan CEO mailinden strateji ekleri toplu forward iç kullanıcıya.",
     "Veri minimizasyonu.", "Toplu forward: 0", "WARNING", "Hız için prosedür atlandı."),
    ("Stajyer Sınav Cevapları", "insider threat", "Stajyer",
     "Stajyer eğitim sunucusundan sınav bankası indiriyor.", "Yetkisiz eğitim verisi.", "İlk erişim", "ALERT", "Arkadaşa paylaşım."),
    # --- dış saldırı desteği (iç göstergeler) ---
    ("İç Spear Phishing", "dış saldırı desteği", "Muhasebe",
     "İç Exchange'den 'Acil şifre yenile' linki; fake-sso credential girişi.",
     "Harvesting iç mail.", "Fake SSO login", "CRITICAL", "Spear phishing."),
    ("SMB Yayılma", "dış saldırı desteği", "Destek Personeli",
     "15 dk'da 40 host SMB445 tarama.", "Lateral spread.", "SMB: 2 → 40", "CRITICAL", "Worm/APT."),
    ("Pass-the-Hash", "dış saldırı desteği", "IT Admin",
     "Tek host'tan admin hash ile 6 sunucu PSRemoting.", "PtH.", "PSRemoting burst", "CRITICAL", "Mimikatz."),
    ("İç DNS TXT", "dış saldırı desteği", "Yazılım Geliştirici",
     "İç DNS'e anormal TXT sorgu hacmi.", "DNS exfil.", "TXT 500x", "ALERT", "C2."),
    ("Stajyer Macro", "dış saldırı desteği", "Stajyer",
     "İç mail Word macro; ardından LDAP enum.", "Malware zinciri.", "Macro+LDAP", "CRITICAL", "Fatura macro."),
    ("Satış Fake IT", "dış saldırı desteği", "Satış",
     "Teams'te sahte IT hesabına OTP kodu gönderildi (iç).", "Sosyal mühendislik.", "OTP paylaşım", "CRITICAL", "Helpdesk taklidi."),
    ("Printer Spooler", "dış saldırı desteği", "Muhasebe",
     "Print-nightmare exploit iç print server'dan SYSTEM denemesi.",
     "Exploit iç ağ.", "Spooler RPC spike", "CRITICAL", "Unpatched print."),
    ("Güvenlik Tool İndirme", "dış saldırı desteği", "Yazılım Geliştirici",
     "İç file server'dan bilinmeyen .exe (mimikatz benzeri hash).", "Malware hash.", "Yeni binary", "CRITICAL", "Kırmızı takım artefaktı kaldı."),
    # --- kazara ihlal ---
    ("Reply-All Fiyat", "kazara ihlal", "Satış",
     "Tüm şirket DL'sine müşteri fiyat listesi eki.", "İç mail sızıntı.", "All-staff+ek", "ALERT", "Reply-all."),
    ("Prod INSERT", "kazara ihlal", "Yazılım Geliştirici",
     "Test script prod HR DB INSERT.", "Prod yazma hatası.", "INSERT: 0", "CRITICAL", "Connection string."),
    ("Everyone ACL", "kazara ihlal", "Proje Yöneticisi",
     "File server'da everyone read ACL.", "Over-permission.", "ACL everyone", "WARNING", "Hızlı paylaşım."),
    ("CEO USB Autorun", "kazara ihlal", "CEO",
     "CEO USB; AV autorun alert.", "Malware giriş.", "USB nadir", "WARNING", "Konferans USB."),
    ("Açık Oturum Muhasebe", "kazara ihlal", "Muhasebe",
     "Paylaşılan PC'de başka oturum açık; muhasebe devam ediyor.", "Session overlap.", "Overlap", "LOG", "Temizlik."),
    ("Admin rm Typo", "kazara ihlal", "IT Admin",
     "Backup script yanlış path 200 GB silme.", "Destructive.", "Delete spike", "CRITICAL", "rm typo."),
    ("İK Yanlış Ek", "kazara ihlal", "İK",
     "İş sözleşmesi taslağı yanlışlıkla tüm-hands iç mail.", "HR veri leak.", "All-hands HR", "ALERT", "Autocomplete."),
    ("Destek Müşteri CC", "kazara ihlal", "Destek Personeli",
     "Ticket yanıtında iç not yerine müşteri PII iç ağ mailine yapıştırıldı.",
     "Yanlış kanal.", "PII iç mail", "WARNING", "Kopyala-yapıştır."),
    # --- politika ihlali ---
    ("Steam 4 Saat", "politika ihlali", "Yazılım Geliştirici",
     "İş istasyonunda Steam 4 saat process.", "Acceptable use.", "Steam 4h", "LOG", "Mola oyunu."),
    ("Mail Forward Kural", "politika ihlali", "İK",
     "İç mailbox forward kuralı kişisel iç mailbox'a.", "Mail policy.", "Yeni kural", "WARNING", "Evden okuma."),
    ("Dual NIC Bypass", "politika ihlali", "Satış",
     "İkinci NIC ile doğrudan file server.", "Segment bypass.", "Dual NIC", "ALERT", "Hız."),
    ("DLP Disable", "politika ihlali", "Stajyer",
     "DLP agent 2 saat disabled.", "Tamper.", "DLP stop", "ALERT", "False positive korkusu."),
    ("Crack Matlab", "politika ihlali", "Veri Analisti",
     "Lisanssız Matlab crack installer.", "Software policy.", "Crack", "WARNING", "Lisans maliyeti."),
    ("Kişisel Cloud Sync", "politika ihlali", "Satış",
     "OneDrive sync client kurulum denemesi (iç policy blok).", "Dış sync yasak.", "Client install", "LOG", "Yedek alışkanlığı."),
    ("Hukuk Torrent", "politika ihlali", "Hukuk",
     "İç ağda BitTorrent benzeri P2P port dinleme (torrent değil update araç).",
     "P2P yasak.", "Port 6881", "WARNING", "Yanlış araç."),
    # --- çapraz departman ---
    ("İK+Muhasebe Collusion", "insider threat", "Muhasebe",
     "Muhasebe+İK aynı dakikada aynı tedarikçi kaydı değişiyor.", "Collusion.", "2 user 1 record", "CRITICAL", "İki kişi bypass."),
    ("Satış→Hukuk Dosya", "veri sızdırma", "Satış",
     "Satış indiriyor; 10 dk sonra Hukuk aynı dosya.", "Zincir transfer.", "Sıralı erişim", "WARNING", "Ortaklık veya sızıntı."),
    ("Dev Deploy SoD", "yetkisiz erişim", "Yazılım Geliştirici",
     "Prod deploy manual trigger; IT onay yok.", "SoD.", "Deploy no ticket", "ALERT", "Cuma baskısı."),
    ("CTO+CFO Gece", "diğer", "CTO",
     "CTO+CFO gece strateji sunucusu.", "Koordinasyon.", "Dual C-level", "LOG", "Board."),
    ("SOC+IT Incident", "diğer", "Güvenlik Görevlisi",
     "SOC+IT log sunucusuna write.", "IR koordinasyon.", "Dual write", "LOG", "Incident."),
    ("PM+Dev Export", "veri sızdırma", "Proje Yöneticisi",
     "PM Jira export + dev git clone aynı proje saat.", "Proje kapanış.", "Correlated", "WARNING", "Teslim."),
    ("Destek CRM PCI", "yetkisiz erişim", "Destek Personeli",
     "CRM kredi kartı alanı görüntüleme.", "PCI.", "CC view", "ALERT", "Gereksiz."),
    ("İK Satış Komisyon", "çapraz - yetkisiz", "İK",
     "İK satış komisyon tablosuna erişiyor; satış müdürü habersiz.",
     "Çapraz HR-finans.", "İlk komisyon erişim", "WARNING", "Şikayet araştırması."),
]

OUT = Path(__file__).resolve().parent.parent / "watchtower-ueba-test-scenarios.md"

def render(scenarios: list[tuple[str, ...]]) -> str:
    lines = [
        "# Watchtower UEBA — Simülasyon Test Senaryoları",
        "",
        f"Toplam: **{len(scenarios)}** senaryo | İç ağ (private LAN) only | 35 çalışan profili",
        "",
        "Kategoriler: veri sızdırma, yetkisiz erişim, insider threat, credential ihlali,",
        "dış saldırı desteği, kazara ihlal, politika ihlali, diğer",
        "",
        "---",
        "",
    ]
    for i, s in enumerate(scenarios, 1):
        lines += [
            f"## {i}. {s[0]}",
            "",
            f"**SENARYO ADI:** {s[0]}",
            f"**KATEGORİ:** {s[1]}",
            f"**KULLANICI ROLÜ:** {s[2]}",
            f"**OLAY:** {s[3]}",
            f"**NEDEN ŞÜPHELİ:** {s[4]}",
            f"**NORMAL BASELINE'DAN SAPMA:** {s[5]}",
            f"**BEKLENEN SEVERITY:** {s[6]}",
            f"**GERÇEKÇİLİK NOTU:** {s[7]}",
            "",
            "---",
            "",
        ]
    return "\n".join(lines)

if __name__ == "__main__":
    OUT.write_text(render(SCENARIOS), encoding="utf-8")
    print(len(SCENARIOS), "->", OUT)
