#!/usr/bin/env python3
"""Generate Watchtower UEBA simulation test scenarios."""

from pathlib import Path

# (name, category, role, olay, neden_supheli, sapma, severity, gerceklik)
SCENARIOS: list[tuple[str, ...]] = [
    ("Gece Yedek Çekimi", "veri sızdırma", "Muhasebe",
     "Muhasebe çalışanı normalde gündüz 200-400 MB finans sunucusundan rapor çekerken Cuma 23:47'de aynı sunucudan 18.4 GB toplu dosya indiriyor; arşiv (.zip) ve CSV paketleri.",
     "Rol için olağandışı saat, tek oturumda 45x veri hacmi, arşiv formatı toplu dışa aktarım paterni.",
     "Günlük ort. 320 MB → 18.4 GB; saat 09-18 dışı ilk kez.", "CRITICAL",
     "İşten ayrılma öncesi veya rakibe veri taşıma girişimlerinde sık görülür."),
    ("USB Toplu Kopya", "veri sızdırma", "Satış",
     "Satış temsilcisi CRM sunucusundan 2.1 GB veriyi 14 dakikada USB'ye kopyalıyor.",
     "Satışta USB yasak; CRM toplu okuma + USB yazma korelasyonu.",
     "USB: ayda 0-1 → 2.1 GB tek sefer.", "ALERT", "Fuar öncesi offline sunum."),
    ("Payroll Dump", "veri sızdırma", "İK",
     "İK uzmanı payroll-db'den tüm maaş tablosunu 890 MB SQL export ile indiriyor.",
     "Tam tablo export; normal iş akışı tek çalışan sorgusu.",
     "Ort. 2-5 MB → 890 MB.", "CRITICAL", "Maaş bilgisi sızdırma/şantaj."),
    ("Kaynak Kod Arşivi", "veri sızdırma", "Yazılım Geliştirici",
     "Geliştirici git-mirror'dan 4.7 GB tüm repo ağacı çekiyor; projesi tek microservice.",
     "Yetkili repo dışı tüm branch çekimi; hafta sonu.",
     "150 MB/hafta → 4.7 GB; repo 1→47.", "ALERT", "Ayrılış öncesi IP biriktirme."),
    ("Hukuk Dava Arşivi", "veri sızdırma", "Hukuk",
     "Hukuk danışmanı dava-arsiv'ten 120 PDF'i ZIP ile 3.2 GB indiriyor.",
     "Toplu indirme; müşteri kodlu dosya adları.",
     "5-10 dosya/gün → 120 dosya.", "WARNING", "Mahkeme hazırlığı meşru olabilir."),
    ("BI Ham PII Export", "veri sızdırma", "Veri Analisti",
     "Analist DWH'den ham müşteri PII ile 12 GB parquet export alıyor.",
     "Dashboard sorgusu 50-200 MB; ham PII export nadir.",
     "12 GB vs ort. 180 MB.", "ALERT", "Yanlış tüm veri seçimi."),
    ("Stajyer CRM Export", "veri sızdırma", "Stajyer",
     "Stajyer 2. haftada CRM'den 45.000 satır müşteri kaydını Excel'e aktarıyor (220 MB).",
     "Stajyer yetkisi demo ortamı; prod export yok.",
     "İlk CRM export; 9x satır üst sınır.", "CRITICAL", "Görev yanlış anlaşılması."),
    ("CFO USB Kopya", "veri sızdırma", "CFO",
     "CFO bütçe sunucusundan 1.8 GB indirip ardından USB'ye kopyalıyor.",
     "İndirme meşru; USB CFO baseline'ında yılda 0.",
     "USB olayı: 0 → 1.8 GB.", "WARNING", "YK sunumu + politika ihlali."),
    ("Destek Ticket PII", "veri sızdırma", "Destek Personeli",
     "Destek attachment store'dan 800 ticket ekini 6.1 GB zip'liyor.",
     "Kimlik fotokopisi ve ekran görüntüsü içerebilir.",
     "50 MB/gün → 6.1 GB.", "ALERT", "Yedekleme bahanesi."),
    ("Admin Yanlış VM", "veri sızdırma", "IT Admin",
     "Admin prod-HR VM snapshot'ını workstation'a 90 GB çekiyor.",
     "Hedef workstation; backup job dışı saat.",
     "Tek sefer 90 GB.", "CRITICAL", "Operasyon hatası."),
    # --- credential ihlali ---
    ("LDAP Bulk Bind", "credential ihlali", "Güvenlik Görevlisi",
     "SOC analisti prod ldap-replica'ya test bind ile 12.000 auth/dk üretiyor.",
     "Test prod'da; rate limit aşımı.", "50 → 12.000 auth/dk", "WARNING", "Pen test unutulmuş."),
    ("Deploy Key 3 IP", "credential ihlali", "Yazılım Geliştirici",
     "svc-deploy API key 3 farklı workstation IP'den kullanılıyor.",
     "Key tek makineye bağlı olmalı.", "Kaynak IP: 1 → 3", "ALERT", "Slack'te key paylaşımı."),
    ("Stajyer Çift Oturum", "credential ihlali", "Stajyer",
     "Stajyer hesabı aynı anda 2 workstation'da aktif; biri mentor masası değil.",
     "Hesap paylaşımı.", "Eşzamanlı oturum: 2 host", "ALERT", "Mentor şifre vermiş."),
    ("CEO Asistan İK", "credential ihlali", "CEO",
     "CEO hesabı İK sunucusuna erişiyor; session fingerprint asistan PC.",
     "İmpersonation riski.", "CEO→İK: yılda 0", "WARNING", "Asistan devri."),
    ("Gece Admin TGT", "credential ihlali", "IT Admin",
     "Admin hesabından 02:00'de 8 sunucuya ardışık Kerberos TGT.",
     "Lateral movement işareti.", "Gece TGT: 0 → 8", "CRITICAL", "PtH sonrası."),
    ("Jira Key Bulk", "credential ihlali", "Proje Yöneticisi",
     "Read-only Jira key ile gece 40.000 issue API çağrısı.",
     "Read-only ile bulk export.", "200/gün → 40.000", "ALERT", "Rapor scripti."),
    ("Paylaşılan RDP", "credential ihlali", "Muhasebe",
     "Muhasebe kullanıcısı başka departman PC'sine RDP; kendi şifresiyle ikinci oturum.",
     "Credential sharing.", "RDP hedef: 0 → 3 farklı host/hafta", "WARNING", "Acil fatura onayı."),
    ("Token Vault Dump", "credential ihlali", "IT Admin",
     "Admin iç HashiCorp Vault audit'te 200 secret read; bakım penceresi dışı.",
     "Secret enumeration.", "Vault read: 5/gün → 200", "CRITICAL", "Compromise veya kötü niyet."),
    ("Stajyer Mentor ADUC", "credential ihlali", "Stajyer",
     "Stajyer RDP ile mentor PC'den ADUC açıyor.",
     "Paylaşılan credential.", "RDP mentor: 0", "ALERT", "Eğitim kötü uygulama."),
    ("CFO Asistan Mail", "credential ihlali", "CFO",
     "CFO mailbox'tan toplu mail silme; client IP asistan subnet.",
     "Yetki devri ihlali.", "Toplu silme: 0", "WARNING", "Temizlik talebi."),
    # --- yetkisiz erişim ---
    ("Satış ERP Erişim", "yetkisiz erişim", "Satış",
     "Satış rep finans-erp'ye RDP; fatura modülü açık.", "Satış grubunda ERP yok.",
     "İlk ERP erişim", "ALERT", "Komisyon araştırması."),
    ("Junior Prod DB", "yetkisiz erişim", "Yazılım Geliştirici",
     "Junior dev prod-db-01 SSMS SELECT *.", "Prod sadece DBA.", "Prod: 0", "CRITICAL", "Bug fix bahanesi."),
    ("Hukuk Performans", "yetkisiz erişim", "Hukuk",
     "Hukuk performans-değerlendirme share'ine erişiyor.", "Dava dışı HR.", "İlk erişim", "WARNING", "İş davası."),
    ("Muhasebe DA Deneme", "yetkisiz erişim", "Muhasebe",
     "Domain Admin grubuna ekleme denemesi başarısız.", "Privilege escalation.", "AD write: 0", "CRITICAL", "Phishing sonrası."),
    ("PM SIEM Konsol", "yetkisiz erişim", "Proje Yöneticisi",
     "PM SIEM web konsoluna login.", "SOC rolü yok.", "İlk SIEM", "ALERT", "Proje inceleme."),
    ("Stajyer Get-ADUser", "yetkisiz erişim", "Stajyer",
     "PowerShell Get-ADUser -Filter *.", "AD okuma yok.", "Cmdlet: 0", "ALERT", "Tutorial."),
    ("CFO Git Gezinme", "yetkisiz erişim", "CFO",
     "CFO git-internal'da repo listesi geziyor.", "C-level kod erişimi yok.", "İlk git", "LOG", "Yanlış link."),
    ("Destek DC RDP", "yetkisiz erişim", "Destek Personeli",
     "Şifre reset için DC'ye RDP.", "DC sadece IT Admin.", "DC RDP: 0", "CRITICAL", "Yanlış prosedür."),
    ("Veri Analisti Prod", "yetkisiz erişim", "Veri Analisti",
     "Analist prod-ml-feature store'a write.", "Prod write yasak.", "Write: 0", "ALERT", "Model güncelleme."),
    ("İK Finans Modül", "yetkisiz erişim", "İK",
     "İK çalışanı finans onay modülünde bekleyen ödemeleri görüntülüyor.", "Çapraz yetki yok.",
     "Finans modül: 0", "WARNING", "Bordro uyumsuzluğu araştırması."),
    ("CTO HR Backup", "yetkisiz erişim", "CTO",
     "CTO hr-backup share'ine yazma denemesi.", "CTO HR write yok.", "Write deneme", "LOG", "Yanlış klasör."),
    # --- insider threat ---
    ("Ayrılış Ramp", "insider threat", "Yazılım Geliştirici",
     "İstifadan 5 gün önce günlük çekim 200 MB→3 GB.", "Offboarding pattern.",
     "5 gün artış", "ALERT", "Klasik insider."),
    ("İK Disiplin Tarama", "insider threat", "İK",
     "İK 12 çalışanın disiplin kaydına bakıyor.", "Need-to-know.", "12 profil", "WARNING", "Dedikodu."),
    ("Satış Segment Model", "insider threat", "Satış",
     "Ayrılan rep müşteri segmentasyon modeline 3 gün erişiyor.", "Rakip verisi.", "Model+ayrılış", "ALERT", "Headhunter."),
    ("Shadow Admin", "insider threat", "IT Admin",
     "Yeni local admin svc_monitor; change ticket yok.", "Shadow account.", "Yeni hesap", "CRITICAL", "Kalıcı erişim."),
    ("Sahte Tedarikçi IBAN", "insider threat", "Muhasebe",
     "Tedarikçi master'da onaysız IBAN değişikliği.", "Fraud.", "Onaysız write", "CRITICAL", "Vendor fraud."),
    ("SOC Log Suppress", "insider threat", "Güvenlik Görevlisi",
     "SOC kendi host için SIEM suppress rule ekliyor.", "Anti-forensics.", "Self suppress", "CRITICAL", "Kendi ihlali."),
    ("PM Maliyet Gizleme", "insider threat", "Proje Yöneticisi",
     "Proje maliyet tablosunda 50 hücre toplu güncelleme.", "Yetkisiz finans write.", "50x write", "ALERT", "Bütçe manipülasyon."),
    ("ML Model Hırsızlık", "insider threat", "Veri Analisti",
     "ML artifact 2.3 GB indirme; export policy ihlal.", "IP hırsızlığı.", "Export: 0", "ALERT", "Yan iş."),
    ("CEO Asistan Strateji", "insider threat", "CEO",
     "Asistan CEO mailinden strateji ekleri toplu forward iç kullanıcıya.",
     "Veri minimizasyonu.", "Toplu forward: 0", "WARNING", "Hız için prosedür atlandı."),
    ("Stajyer Sınav Cevapları", "insider threat", "Stajyer",
     "Stajyer eğitim sunucusundan sınav bankası indiriyor.", "Yetkisiz eğitim verisi.", "İlk erişim", "ALERT", "Arkadaşa paylaşım."),
    # --- dış saldırı desteği (iç göstergeler) ---
    ("İç Spear Phishing", "dış saldırı desteği", "Muhasebe",
     "İç Exchange'den 'Acil şifre yenile' linki; fake-sso credential girişi.",
     "Harvesting iç mail.", "Fake SSO login", "CRITICAL", "Spear phishing."),
    ("SMB Yayılma", "dış saldırı desteği", "Destek Personeli",
     "15 dk'da 40 host SMB445 tarama.", "Lateral spread.", "SMB: 2 → 40", "CRITICAL", "Worm/APT."),
    ("Pass-the-Hash", "dış saldırı desteği", "IT Admin",
     "Tek host'tan admin hash ile 6 sunucu PSRemoting.", "PtH.", "PSRemoting burst", "CRITICAL", "Mimikatz."),
    ("İç DNS TXT", "dış saldırı desteği", "Yazılım Geliştirici",
     "İç DNS'e anormal TXT sorgu hacmi.", "DNS exfil.", "TXT 500x", "ALERT", "C2."),
    ("Stajyer Macro", "dış saldırı desteği", "Stajyer",
     "İç mail Word macro; ardından LDAP enum.", "Malware zinciri.", "Macro+LDAP", "CRITICAL", "Fatura macro."),
    ("Satış Fake IT", "dış saldırı desteği", "Satış",
     "Teams'te sahte IT hesabına OTP kodu gönderildi (iç).", "Sosyal mühendislik.", "OTP paylaşım", "CRITICAL", "Helpdesk taklidi."),
    ("Printer Spooler", "dış saldırı desteği", "Muhasebe",
     "Print-nightmare exploit iç print server'dan SYSTEM denemesi.",
     "Exploit iç ağ.", "Spooler RPC spike", "CRITICAL", "Unpatched print."),
    ("Güvenlik Tool İndirme", "dış saldırı desteği", "Yazılım Geliştirici",
     "İç file server'dan bilinmeyen .exe (mimikatz benzeri hash).", "Malware hash.", "Yeni binary", "CRITICAL", "Kırmızı takım artefaktı kaldı."),
    # --- kazara ihlal ---
    ("Reply-All Fiyat", "kazara ihlal", "Satış",
     "Tüm şirket DL'sine müşteri fiyat listesi eki.", "İç mail sızıntı.", "All-staff+ek", "ALERT", "Reply-all."),
    ("Prod INSERT", "kazara ihlal", "Yazılım Geliştirici",
     "Test script prod HR DB INSERT.", "Prod yazma hatası.", "INSERT: 0", "CRITICAL", "Connection string."),
    ("Everyone ACL", "kazara ihlal", "Proje Yöneticisi",
     "File server'da everyone read ACL.", "Over-permission.", "ACL everyone", "WARNING", "Hızlı paylaşım."),
    ("CEO USB Autorun", "kazara ihlal", "CEO",
     "CEO USB; AV autorun alert.", "Malware giriş.", "USB nadir", "WARNING", "Konferans USB."),
    ("Açık Oturum Muhasebe", "kazara ihlal", "Muhasebe",
     "Paylaşılan PC'de başka oturum açık; muhasebe devam ediyor.", "Session overlap.", "Overlap", "LOG", "Temizlik."),
    ("Admin rm Typo", "kazara ihlal", "IT Admin",
     "Backup script yanlış path 200 GB silme.", "Destructive.", "Delete spike", "CRITICAL", "rm typo."),
    ("İK Yanlış Ek", "kazara ihlal", "İK",
     "İş sözleşmesi taslağı yanlışlıkla tüm-hands iç mail.", "HR veri leak.", "All-hands HR", "ALERT", "Autocomplete."),
    ("Destek Müşteri CC", "kazara ihlal", "Destek Personeli",
     "Ticket yanıtında iç not yerine müşteri PII iç ağ mailine yapıştırıldı.",
     "Yanlış kanal.", "PII iç mail", "WARNING", "Kopyala-yapıştır."),
    # --- politika ihlali ---
    ("Steam 4 Saat", "politika ihlali", "Yazılım Geliştirici",
     "İş istasyonunda Steam 4 saat process.", "Acceptable use.", "Steam 4h", "LOG", "Mola oyunu."),
    ("Mail Forward Kural", "politika ihlali", "İK",
     "İç mailbox forward kuralı kişisel iç mailbox'a.", "Mail policy.", "Yeni kural", "WARNING", "Evden okuma."),
    ("Dual NIC Bypass", "politika ihlali", "Satış",
     "İkinci NIC ile doğrudan file server.", "Segment bypass.", "Dual NIC", "ALERT", "Hız."),
    ("DLP Disable", "politika ihlali", "Stajyer",
     "DLP agent 2 saat disabled.", "Tamper.", "DLP stop", "ALERT", "False positive korkusu."),
    ("Crack Matlab", "politika ihlali", "Veri Analisti",
     "Lisanssız Matlab crack installer.", "Software policy.", "Crack", "WARNING", "Lisans maliyeti."),
    ("Kişisel Cloud Sync", "politika ihlali", "Satış",
     "OneDrive sync client kurulum denemesi (iç policy blok).", "Dış sync yasak.", "Client install", "LOG", "Yedek alışkanlığı."),
    ("Hukuk Torrent", "politika ihlali", "Hukuk",
     "İç ağda BitTorrent benzeri P2P port dinleme (torrent değil update araç).",
     "P2P yasak.", "Port 6881", "WARNING", "Yanlış araç."),
    # --- çapraz departman ---
    ("İK+Muhasebe Collusion", "insider threat", "Muhasebe",
     "Muhasebe+İK aynı dakikada aynı tedarikçi kaydı değişiyor.", "Collusion.", "2 user 1 record", "CRITICAL", "İki kişi bypass."),
    ("Satış→Hukuk Dosya", "veri sızdırma", "Satış",
     "Satış indiriyor; 10 dk sonra Hukuk aynı dosya.", "Zincir transfer.", "Sıralı erişim", "WARNING", "Ortaklık veya sızıntı."),
    ("Dev Deploy SoD", "yetkisiz erişim", "Yazılım Geliştirici",
     "Prod deploy manual trigger; IT onay yok.", "SoD.", "Deploy no ticket", "ALERT", "Cuma baskısı."),
    ("CTO+CFO Gece", "diğer", "CTO",
     "CTO+CFO gece strateji sunucusu.", "Koordinasyon.", "Dual C-level", "LOG", "Board."),
    ("SOC+IT Incident", "diğer", "Güvenlik Görevlisi",
     "SOC+IT log sunucusuna write.", "IR koordinasyon.", "Dual write", "LOG", "Incident."),
    ("PM+Dev Export", "veri sızdırma", "Proje Yöneticisi",
     "PM Jira export + dev git clone aynı proje saat.", "Proje kapanış.", "Correlated", "WARNING", "Teslim."),
    ("Destek CRM PCI", "yetkisiz erişim", "Destek Personeli",
     "CRM kredi kartı alanı görüntüleme.", "PCI.", "CC view", "ALERT", "Gereksiz."),
    ("İK Satış Komisyon", "yetkisiz erişim", "İK",
     "İK satış komisyon tablosuna erişiyor; satış müdürü habersiz.",
     "Çapraz HR-finans.", "İlk komisyon erişim", "WARNING", "Şikayet araştırması."),
    # --- Batch 2: rol ve veri tipi çeşitliliği ---
    ("Muhasebe Gece ERP", "veri sızdırma", "Muhasebe",
     "Pazar 01:12'de ERP'den 5 yıllık genel muhasebe defteri 4.2 GB export.",
     "Hafta sonu gece; tam defter export.", "Saat+ hacim 20x", "CRITICAL", "Yıl kapanışı kopyası."),
    ("Satış Pipeline Dump", "veri sızdırma", "Satış",
     "Satış pipeline DB'den tüm fırsatlar+marj 1.1 GB; normal günlük 15 MB dashboard.",
     "Marj verisi toplu.", "1.1 GB vs 15 MB", "ALERT", "Rakip işe geçiş."),
    ("Güvenlik IOC List", "veri sızdırma", "Güvenlik Görevlisi",
     "SOC threat-intel share'den 600 MB IOC paketi USB'ye.",
     "SOC USB nadir; IOC dışarı değerli.", "USB 600 MB", "WARNING", "Konferans sunumu."),
    ("Proje Yöneticisi SOW", "veri sızdırma", "Proje Yöneticisi",
     "Tüm aktif SOW ve teklif PDF'leri 2.8 GB tek sefer.",
     "Müşteri fiyatları içerir.", "50 dosya vs 3", "ALERT", "Taşeron paylaşımı."),
    ("Destek Şifre Reset Log", "credential ihlali", "Destek Personeli",
     "1 saatte 35 kullanıcı şifre reset; normal 3-5.", "Account takeover hazırlığı.",
     "Reset: 5 → 35", "CRITICAL", "Sosyal mühendislik sonrası."),
    ("CTO API Key Rotate", "credential ihlali", "CTO",
     "CTO tech-radar API key eski key ile hâlâ 200 call; rotate sonrası.",
     "Rotate sonrası eski key.", "Eski key aktif", "WARNING", "Otomasyon güncellenmemiş."),
    ("İK Bordro Toplu Mail", "kazara ihlal", "İK",
     "Bordro ekleri yanlış departman DL'sine.", "Maaş leak.", "DL yanlış", "CRITICAL", "Outlook autocomplete."),
    ("Yazılım Secrets Repo", "veri sızdırma", "Yazılım Geliştirici",
     "secrets-repo'dan 40 .env dosyası indirme.", "Credential dosyaları.", "40 dosya", "CRITICAL", "Acil prod fix."),
    ("CFO Tax Audit Pack", "veri sızdırma", "CFO",
     "Vergi denetim paketi 6 GB indirme meşru; ardından yazdırma kuyruğu 4000 sayfa.",
     "Fiziksel exfil riski.", "Print spike", "WARNING", "Denetim meşru."),
    ("Stajyer SharePoint", "yetkisiz erişim", "Stajyer",
     "Stajyer yönetim kurulu SharePoint library browse.",
     "Board library yasak.", "İlk erişim", "ALERT", "Link paylaşıldı."),
    ("IT Admin GPO Değişik", "insider threat", "IT Admin",
     "USB disable GPO devre dışı; change yok.", "Policy weaken.", "GPO change", "CRITICAL", "Kendi exfil için."),
    ("Muhasebe Çift Onay Bypass", "insider threat", "Muhasebe",
     "50.000 TL üzeri ödeme tek onayla geçirilmiş.", "SoD ihlali.", "Tek onay", "CRITICAL", "Fraud."),
    ("Satış İç Rakip Mail", "insider threat", "Satış",
     "Satış iç mailde rakip firma adı+teklif detayı forward.", "Rekabet ihlali.", "Rakip keyword", "WARNING", "Müşteri şikayeti."),
    ("Hukuk Privileged Mail", "veri sızdırma", "Hukuk",
     "Attorney-client privileged klasör 1.5 GB indirme.",
     "Ayrıcalıklı içerik toplu.", "1.5 GB", "ALERT", "Dış hukuk bürosu."),
    ("Veri Analisti Maskesiz", "politika ihlali", "Veri Analisti",
     "DWH sorgusunda PII mask kaldırılmış kolonlar.", "Mask bypass.", "Mask off", "ALERT", "Analiz kolaylığı."),
    ("CEO Takvim Export", "veri sızdırma", "CEO",
     "CEO Exchange takvim 3 yıl .ics export 40 MB.", "Strateji toplantıları.", "İlk export", "LOG", "Asistan yedek."),
    ("Güvenlik Yanlış Quarantine", "kazara ihlal", "Güvenlik Görevlisi",
     "SOC yanlışlıkla finans batch dosyasını quarantine.", "İş kesintisi.", "False positive", "LOG", "İmzası benzer malware."),
    ("Destek RDP Müşteri", "politika ihlali", "Destek Personeli",
     "Müşteri demo için uzun süre ekran paylaşım kaydı iç sunucuda.", "Kayıt policy.", "8 saat kayıt", "WARNING", "Eğitim videosu."),
    ("PM Jira Admin", "yetkisiz erişim", "Proje Yöneticisi",
     "PM Jira admin panelinde kullanıcı silme denemesi.", "Admin yetkisi yok.", "Delete user", "ALERT", "Temizlik."),
    ("Yazılım CI Token", "credential ihlali", "Yazılım Geliştirici",
     "CI token ile artifact registry'den 30 container image pull gece.",
     "Gece toplu pull.", "30 image", "WARNING", "Yerel test."),
    ("İK Sağlık Verisi", "veri sızdırma", "İK",
     "Sağlık sigortası claim kayıtları 120 çalışan 450 MB.", "Hassas sağlık.", "450 MB", "CRITICAL", "KVKK ihlali riski."),
    ("Muhasebe VPN İç", "diğer", "Muhasebe",
     "Muhasebe evden VPN ile ERP; normal. Ancak aynı anda ofis workstation aktif.",
     "İki lokasyon aynı kullanıcı.", "Dual location", "WARNING", "VPN açık unutulmuş."),
    ("Satış Demo DB", "yetkisiz erişim", "Satış",
     "Satış demo-db'ye değil prod-crm'e bağlanmış connection string.",
     "Prod CRM satışta kısıtlı.", "Prod bağlantı", "ALERT", "Config hatası."),
    ("Stajyer Printer", "kazara ihlal", "Stajyer",
     "Stajyer confidential yazıcı kuyruğuna 200 sayfa CV baskı.", "Yanlış printer.", "Confidential queue", "LOG", "Yanlış seçim."),
    ("IT Admin SNMP", "dış saldırı desteği", "IT Admin",
     "Compromised host SNMP community string ile 50 switch poll.",
     "Reconnaissance.", "SNMP burst", "ALERT", "Monitoring tool taklidi."),
    ("CTO Lab Sunucu", "yetkisiz erişim", "CTO",
     "CTO prod-payment'e lab credential ile bağlanma denemesi.", "Lab cred prod'da.", "Cross cred", "CRITICAL", "Yanlış env."),
    ("CFO Hedge Model", "veri sızdırma", "CFO",
     "Finans modeling sunucusundan hedge senaryoları 900 MB.",
     "CFO yetkili; USB follow.", "USB after", "WARNING", "Danışman paylaşımı."),
    ("Güvenlik Honeypot", "diğer", "Güvenlik Görevlisi",
     "Honeypot share'e erişim; gerçek saldırgan değil pentest.",
     "Honeypot tetik.", "Expected", "LOG", "Kırmızı takım."),
    ("Yazılım Dependency Confusion", "dış saldırı desteği", "Yazılım Geliştirici",
     "İç artifact repo'ya bilinmeyen paket publish denemesi.",
     "Supply chain.", "Publish deneme", "CRITICAL", "Poisoned package."),
    ("İK Exit Interview", "insider threat", "İK",
     "Ayrılan çalışanın exit interview kaydı 8 kişiye forward.",
     "Gizlilik.", "8 recipient", "WARNING", "Prosedür ihlali."),
    ("Muhasebe E-Fatura", "veri sızdırma", "Muhasebe",
     "E-fatura arşiv sunucusundan 1 yıl XML 3.5 GB.", "Toplu arşiv.", "3.5 GB", "ALERT", "Mali müşavir."),
    ("Satış Ses Kaydı", "politika ihlali", "Satış",
     "Müşteri görüşme ses kaydı izinsiz paylaşım klasörüne.", "Kayıt onayı yok.", "Share upload", "ALERT", "Kalite kontrol bahanesi."),
    ("Destek Admin Panel", "credential ihlali", "Destek Personeli",
     "Destek hesabı ile admin-helpdesk impersonation 12 kullanıcı.",
     "Impersonation abuse.", "12 impersonate", "CRITICAL", "Hızlı çözüm."),
    ("Proje Yöneticisi Timesheet", "insider threat", "Proje Yöneticisi",
     "PM 4 çalışanın timesheet'ini onaysız düzenliyor.", "Timesheet fraud.", "4 user edit", "WARNING", "Proje maliyeti düşürme."),
    ("Veri Analisti Notebook", "veri sızdırma", "Veri Analisti",
     "Jupyter notebook output 800 MB iç PII cache.", "Cache leak.", "800 MB cache", "ALERT", "Notebook unutulmuş."),
    ("CEO Driver USB", "kazara ihlal", "CEO",
     "Şoför CEO laptop'a USB takıyor (şarj+cihaz).", "Üçüncü taraf USB.", "Foreign USB", "WARNING", "Şarj kablosu."),
    ("Hukuk e-Discovery", "veri sızdırma", "Hukuk",
     "e-Discovery export 12 GB PST iç mail.", "Büyük PST.", "12 GB", "ALERT", "Dava meşru."),
    ("Stajyer Git Push", "yetkisiz erişim", "Stajyer",
     "Stajyer read-only repo'ya push denemesi başarısız.", "Write deneme.", "Push fail", "LOG", "Tutorial hatası."),
    ("IT Admin DHCP Rogue", "insider threat", "IT Admin",
     "Yeni DHCP scope office VLAN; değişiklik kaydı yok.", "Rogue DHCP.", "New scope", "CRITICAL", "MITM hazırlığı."),
    ("Muhasebe KDV List", "veri sızdırma", "Muhasebe",
     "KDV iade listesi tüm müşteriler 600 MB Excel.", "Müşteri vergi no.", "600 MB", "ALERT", "Müşavir."),
    ("Satış Whatsapp İç", "politika ihlali", "Satış",
     "İç mail yerine kişisel whatsapp web iç PC'de müşteri telefon.", "Kanal policy.", "WhatsApp web", "LOG", "Alışkanlık."),
    ("İK Org Chart Export", "veri sızdırma", "İK",
     "Tam organizasyon+telefon+doğum tarihi export.", "PII aggregate.", "Full org", "WARNING", "Sunum."),
    ("Yazılım Log4j Scan", "dış saldırı desteği", "Yazılım Geliştirici",
     "İç vulnerability scanner tüm hostlara JNDI probe.", "Scanner veya saldırı.", "Probe 200 host", "WARNING", "Patch taraması."),
    ("Güvenlik Firewall Rule", "insider threat", "Güvenlik Görevlisi",
     "Geçici allow rule süresi dolmadan kalıcı yapılmış.", "Rule persist.", "Expired rule", "ALERT", "Acil açık unutulmuş."),
    ("CFO Bank Swift", "veri sızdırma", "CFO",
     "SWIFT mesaj arşivi 2 GB indirme.", "Finansal mesajlar.", "2 GB", "CRITICAL", "Siber soygun hazırlığı."),
    ("Destek Passphrase", "credential ihlali", "Destek Personeli",
     "Destek ticket'ta kullanıcı şifresi plaintext yazmış.", "Secret in ticket.", "Plaintext pwd", "ALERT", "Kullanıcı verdi."),
    ("PM Risk Register", "veri sızdırma", "Proje Yöneticisi",
     "Risk register tüm projeler 400 MB.", "Stratejik riskler.", "400 MB", "WARNING", "Audit."),
    ("Veri Analisti Cross Dept", "yetkisiz erişim", "Veri Analisti",
     "İK attrition modeline erişim; sadece satış churn yetkili.", "Model scope.", "İK model", "WARNING", "Merak."),
    ("Stajyer Cafeteria", "diğer", "Stajyer",
     "Stajyer kartı ile gece 02:00 fiziksel giriş+aynı anda VPN.", "Fiziksel+logical.", "02:00 entry", "LOG", "Projede kalmış."),
    ("IT Admin WSUS", "kazara ihlal", "IT Admin",
     "Yanlış patch ring'e finans sunucuları dahil; reboot planlandı.", "Change risk.", "Wrong ring", "ALERT", "Grup hatası."),
    ("Muhasebe+Satış Ortak USB", "insider threat", "Muhasebe",
     "Aynı USB cihaz ID 2 farklı kullanıcıda 1 saat arayla.", "Ortak exfil aracı.", "Same USB ID", "CRITICAL", "İki kişi collusion."),
    ("Hukuk+CEO Sözleşme", "çapraz erişim", "Hukuk",
     "Hukuk CEO sözleşme klasörüne erişim; merger hazırlığı duyulmadı.",
     "Erken bilgi.", "CEO contract", "WARNING", "Gizli proje."),
    ("Yazılım+IT Secret Rotate", "diğer", "IT Admin",
     "IT rotate ederken dev pipeline kırıldı; dev eski secret ile 500 retry.",
     "Chaos değil saldırı.", "500 retry", "LOG", "Koordinasyon eksik."),
    ("Satış+Destek Müşteri PII", "veri sızdırma", "Destek Personeli",
     "Destek ticket'tan PII kopyalayıp satış CRM notuna yapıştırma.", "PII yayılım.", "CRM note PII", "WARNING", "Hız."),
    ("İK+Güvenlik Offboard", "diğer", "Güvenlik Görevlisi",
     "Ayrılan IT admin hesabı disable gecikmesi 48 saat; hâlâ VPN.", "Offboard SLA.", "48h active", "CRITICAL", "İK bildirimi gecikti."),
    ("Stajyer+Muhasebe Fatura", "yetkisiz erişim", "Stajyer",
     "Stajyer muhasebe ortak ekranda fatura onay tıklıyor.", "Yetkisiz onay.", "Approve click", "ALERT", "Shadowing hatası."),
    ("CEO+CTO Patent", "veri sızdırma", "CTO",
     "Patent başvuru taslakları 1.2 GB indirme.", "IP kritik.", "1.2 GB", "ALERT", "Patent avukatı."),
    ("CFO+İK Headcount", "insider threat", "CFO",
     "CFO gizli headcount reduction listesine İK'dan erken erişim.", "Insider trading risk.", "Pre-announce", "WARNING", "Sızıntı."),
    ("Güvenlik+Yazılım Backdoor", "dış saldırı desteği", "Yazılım Geliştirici",
     "Commit'te obfuscated reverse shell; iç git.", "Backdoor.", "Shell signature", "CRITICAL", "Supply chain."),
    ("Proje+Veri Feature Leak", "veri sızdırma", "Veri Analisti",
     "Üretim feature store'dan test ortama 5 GB kopya.", "Prod→test data.", "5 GB copy", "ALERT", "Test realism."),
    ("Satış Gece CRM", "insider threat", "Satış",
     "Ayrılan rep Cumartesi 03:00 CRM export.", "Off hours+export.", "03:00", "CRITICAL", "Rakip."),
    ("Muhasebe API Fraud", "credential ihlali", "Muhasebe",
     "Banka entegrasyon API key workstation registry'de plaintext.", "Secret storage.", "Registry key", "CRITICAL", "Eski entegrasyon."),
    ("İK Sosyal Mühendislik", "dış saldırı desteği", "İK",
     "İK'ya sahte CEO mail 'acil maaş listesi' ; İK tıklamadı.", "Hedef İK.", "Blocked", "LOG", "CEO fraud."),
    ("Destek Tool İndir", "dış saldırı desteği", "Destek Personeli",
     "Remote tool (TeamViewer benzeri) kurulum iç PC.", "Remote tool policy.", "Install", "ALERT", "Müşteri desteği."),
    ("IT VLAN Hop", "dış saldırı desteği", "IT Admin",
     "Compromised PC finance VLAN'a route add.", "VLAN hop.", "New route", "CRITICAL", "Segmentation bypass."),
    ("CEO Asistan Toplantı", "politika ihlali", "CEO",
     "Gizli yönetim toplantısı kaydı paylaşım linki iç chat.", "Gizli kayıt.", "Chat link", "WARNING", "Not alma."),
    ("Hukuk Metadata", "veri sızdırma", "Hukuk",
     "Word dosyalarında eski revision metadata ile 200 dosya.", "Hidden metadata.", "200 doc", "LOG", "Eski avukat notları."),
    ("Stajyer Phishing Test", "diğer", "Stajyer",
     "Stajyer güvenlik phishing simülasyonuna tıkladı.", "Eğitim metrik.", "Clicked", "LOG", "Beklenen eğitim."),
    ("Yazılım DB Backup Local", "veri sızdırma", "Yazılım Geliştirici",
     "Dev local disk'e prod DB backup restore 15 GB.", "Prod data local.", "15 GB local", "CRITICAL", "Debug."),
    ("Güvenlik Nmap İç", "politika ihlali", "Güvenlik Görevlisi",
     "Onaysız nmap tüm /16 iç subnet.", "Scan policy.", "Full /16", "WARNING", "Pentest."),
    ("CFO Expense Fraud", "insider threat", "CFO",
     "CFO kendi expense raporunda onay zinciri bypass (sistem bug).", "SoD anomaly.", "Self approve", "ALERT", "Nadir bug."),
    ("Muhasebe Zaman Damgası", "diğer", "Muhasebe",
     "Sistem saati geri alınmış PC'de fatura tarihi manipülasyon denemesi.", "Time tamper.", "Clock skew", "CRITICAL", "Fraud."),
    ("Satış Lisans Anahtarı", "credential ihlali", "Satış",
     "Satış CRM lisans anahtarını iç wiki'ye yapıştırma.", "Secret in wiki.", "Wiki paste", "ALERT", "Kolay erişim."),
    ("İK BGB Eğitim", "politika ihlali", "İK",
     "Zorunlu KVKK eğitimi 3. kez atlandı; sistem uyarı.", "Compliance.", "Skipped x3", "LOG", "Yoğunluk."),
    ("Destek DB Sorgu", "yetkisiz erişim", "Destek Personeli",
     "Destek read-only ticket DB'de UPDATE denemesi.", "SQL injection test değil abuse.", "UPDATE", "ALERT", "Merak."),
    ("PM Bütçe Excel Makro", "dış saldırı desteği", "Proje Yöneticisi",
     "Bütçe Excel macro enabled; dışarıdan değil iç mail eki.", "Macro risk.", "Macro run", "WARNING", "Eski şablon."),
    ("Veri Analisti GPU Farm", "yetkisiz erişim", "Veri Analisti",
     "GPU cluster admin queue'ya başka departman job submit.", "Kaynak hog.", "Foreign job", "LOG", "Uzun eğitim."),
    ("Stajyer Slack Token", "credential ihlali", "Stajyer",
     "Stajyer bot token'ı public iç channel'a yapıştırma.", "Token leak.", "Channel paste", "CRITICAL", "Yardım istedi."),
    ("IT Admin Hypervisor", "yetkisiz erişim", "IT Admin",
     "Admin kişisel AD hesabıyla hypervisor console; ayrı admin hesabı policy.", "Dual account policy.", "Personal on HV", "WARNING", "Acil reboot."),
    ("CEO Physical+Data", "insider threat", "CEO",
     "CEO after hours bina girişi + aynı saat strateji sunucu 2 GB.", "Korelasyon.", "Physical+data", "WARNING", "Board hazırlık."),
    ("CTO Open Source Mirror", "veri sızdırma", "CTO",
     "İç oss-mirror'dan tüm tarball 8 GB.", "Mirror tam çekim.", "8 GB", "LOG", "Air-gap mirror kurulum."),
    ("Güvenlik Alert Fatigue", "diğer", "Güvenlik Görevlisi",
     "SOC 200 alert'i bulk close without investigation.", "Process violation.", "Bulk close", "WARNING", "Vardiya sonu."),
    ("Yazılım Composer Token", "credential ihlali", "Yazılım Geliştirici",
     "AI IDE token iç git commit'te.", "Secret in git.", "Token in repo", "CRITICAL", "Yanlış commit."),
    ("Muhasebe Yinelenen Ödeme", "insider threat", "Muhasebe",
     "Aynı fatura 2 kez ödeme; farklı referans.", "Duplicate pay.", "2x payment", "ALERT", "Hata veya fraud."),
    ("Satış Müşteri Şikayet", "kazara ihlal", "Satış",
     "Müşteri şikayet detayı iç all-sales mail.", "Müşteri PII.", "All-sales", "WARNING", "Öfke maili."),
    ("İK Referans Check", "veri sızdırma", "İK",
     "Aday CV+referans 50 paket 300 MB indirme.", "Toplu aday.", "300 MB", "LOG", "İşe alım."),
    ("Hukuk İç Soruşturma", "insider threat", "Hukuk",
     "Soruşturma dosyasına ilgili çalışan erişiyor (conflict).", "Conflict of interest.", "Subject access", "CRITICAL", "Adalet."),
    ("Destek Kiosk Login", "credential ihlali", "Destek Personeli",
     "Ortak kiosk'ta admin oturumu kapatılmamış.", "Shared kiosk.", "Open admin", "ALERT", "Vardiya değişimi."),
    ("Proje Yöneticisi Vendor", "insider threat", "Proje Yöneticisi",
     "PM vendor listesine kendi şirketini ekleme denemesi.", "Conflict.", "Self vendor", "CRITICAL", "Kickback."),
    ("Veri Analisti Synthetic", "diğer", "Veri Analisti",
     "Sentetik veri üretimi 10 GB; normal.", "Baseline genişleme.", "10 GB synth", "LOG", "Yeni model."),
    ("Stajyer İlk Gün Scan", "dış saldırı desteği", "Stajyer",
     "Stajyer ilk gün tüm network share listeleme script.", "Recon.", "Share enum", "WARNING", "Merak/hacking culture."),
    ("IT Admin Cert Expiry", "kazara ihlal", "IT Admin",
     "İç TLS cert expire; finans API hata.", "Avail impact.", "Cert expired", "ALERT", "Renewal unutuldu."),
    ("CEO+CFO+CTO Board", "diğer", "CEO",
     "Üç C-level aynı saat board sunucusu; normal quarterly.", "Expected cluster.", "Quarterly", "LOG", "Board."),
    ("Muhasebe Eski Sürüm", "politika ihlali", "Muhasebe",
     "Desteklenmeyen Excel 2010 ile macro dosya açma.", "EOL software.", "Excel 2010", "LOG", "Uyumluluk."),
    ("Satış+İK Çapraz Mail", "kazara ihlal", "Satış",
     "Satış performans düşüklüğü maili yanlışlıkla çalışana gitti.", "HR sensitive.", "Wrong recipient", "ALERT", "Otomatik tamamlama."),
    ("Yazılım Container Escape", "dış saldırı desteği", "Yazılım Geliştirici",
     "Dev container'dan host mount /etc/shadow read denemesi.", "Escape.", "Shadow read", "CRITICAL", "CVE exploit."),
    ("Güvenlik SIEM Rule Test", "diğer", "Güvenlik Görevlisi",
     "Kasıtlı test event 50 kez üretildi.", "Test noise.", "50 test", "LOG", "Rule tuning."),
    ("İK Çalışan Foto", "veri sızdırma", "İK",
     "Tüm çalışan fotoğraf arşivi 1.8 GB.", "Biyometrik/PII.", "1.8 GB", "WARNING", "Yeni ID kart."),
    ("CFO Treasury", "yetkisiz erişim", "CFO",
     "CFO treasury trading sistemi read; normalde sadece rapor.", "Trading access.", "Trading UI", "WARNING", "Piyasa kontrolü."),
    ("Destek Shadow IT", "politika ihlali", "Destek Personeli",
     "İç sunucuda kurulu yetkisiz PostgreSQL instance.", "Shadow IT.", "New service", "ALERT", "Ticket DB."),
    ("PM Agile Board Export", "veri sızdırma", "Proje Yöneticisi",
     "Sprint board tüm geçmiş 5 yıl JSON 1 GB.", "Uzun tarih.", "5 yıl", "LOG", "Retrospektif."),
    ("Veri Analisti Outlier", "diğer", "Veri Analisti",
     "Analist kendi hesabında normal çalışma; sistem false positive testi.", "Control case.", "Normal", "LOG", "Negative test."),
]

OUT = Path(__file__).resolve().parent.parent / "watchtower-ueba-test-scenarios.md"

def render(scenarios: list[tuple[str, ...]]) -> str:
    lines = [
        "# Watchtower UEBA — Simülasyon Test Senaryoları",
        "",
        f"Toplam: **{len(scenarios)}** senaryo | İç ağ (private LAN) only | 35 çalışan profili",
        "",
        "Kategoriler: veri sızdırma, yetkisiz erişim, insider threat, credential ihlali,",
        "dış saldırı desteği, kazara ihlal, politika ihlali, diğer",
        "",
        "---",
        "",
    ]
    for i, s in enumerate(scenarios, 1):
        lines += [
            f"## {i}. {s[0]}",
            "",
            f"**SENARYO ADI:** {s[0]}",
            f"**KATEGORİ:** {s[1]}",
            f"**KULLANICI ROLÜ:** {s[2]}",
            f"**OLAY:** {s[3]}",
            f"**NEDEN ŞÜPHELİ:** {s[4]}",
            f"**NORMAL BASELINE'DAN SAPMA:** {s[5]}",
            f"**BEKLENEN SEVERITY:** {s[6]}",
            f"**GERÇEKÇİLİK NOTU:** {s[7]}",
            "",
            "---",
            "",
        ]
    return "\n".join(lines)

if __name__ == "__main__":
    OUT.write_text(render(SCENARIOS), encoding="utf-8")
    print(len(SCENARIOS), "->", OUT)
