options {
    directory "/var/cache/bind";
    listen-on port 53 { any; };
    allow-query { any; };
    recursion yes;
    forwarders { 1.1.1.1; };
};

zone "corp.local" IN {
    type master;
    file "/etc/bind/zones/corp.local.zone";
};

zone "0.28.172.in-addr.arpa" IN {
    type master;
    file "/etc/bind/zones/reverse.zone";
};
