options {
    directory "/var/cache/bind";
    listen-on port 53 { any; };
    allow-query { any; };
    recursion yes;
    forwarders { 1.1.1.1; };
};

logging {
    channel query_log {
        file "/var/log/corp/dns/query.log" versions 3 size 10m;
        severity info;
        print-category yes;
        print-severity yes;
    };
    category queries { query_log; };
};

zone "corp.local" IN {
    type master;
    file "/etc/bind/zones/corp.local.zone";
};

zone "0.28.172.in-addr.arpa" IN {
    type master;
    file "/etc/bind/zones/reverse.zone";
};
