"""Source data for Phase 0 feature/scenario coverage manifests."""

from __future__ import annotations

# Plan §3.1 — phase, simulation_source, evidence_expected
FEATURE_MATRIX: list[dict] = [
    {"id": "F-001", "phase": 1, "simulation_source": "Samba file audit + Zeek/synthetic SMB flow", "evidence_expected": "SMB read volume event"},
    {"id": "F-002", "phase": 1, "simulation_source": "Zeek conn.log + east-west flow generator", "evidence_expected": "host/port fan-out event"},
    {"id": "F-003", "phase": 1, "simulation_source": "BIND query log + DNS entropy generator", "evidence_expected": "TXT/NXDOMAIN/high-entropy query event"},
    {"id": "F-004", "phase": 1, "simulation_source": "SMB downgrade synthetic packet/log generator", "evidence_expected": "SMBv1/NTLMv1 downgrade attempt"},
    {"id": "F-005", "phase": 1, "simulation_source": "DHCP server log + rogue DHCP/ARP generator", "evidence_expected": "duplicate lease/scope change event"},
    {"id": "F-006", "phase": 1, "simulation_source": "Samba AD auth log + failed/success login replay", "evidence_expected": "4625 burst then 4624 success"},
    {"id": "F-007", "phase": 1, "simulation_source": "Zeek conn.log + port scan replay", "evidence_expected": "high cardinality port scan event"},
    {"id": "F-008", "phase": 1, "simulation_source": "Samba AD Kerberos/NTLM synthetic auth log", "evidence_expected": "TGT/NTLM target diversity event"},
    {"id": "F-009", "phase": 3, "simulation_source": "Badge API + AD login replay + switch-port mock", "evidence_expected": "same user multi-location session"},
    {"id": "F-010", "phase": 1, "simulation_source": "Samba AD login event generator", "evidence_expected": "service account interactive logon"},
    {"id": "F-011", "phase": 1, "simulation_source": "Samba AD group-change replay", "evidence_expected": "privileged group add/remove event"},
    {"id": "F-012", "phase": 3, "simulation_source": "API gateway mock + Vault audit + app access log", "evidence_expected": "API key multi-source usage"},
    {"id": "F-013", "phase": 3, "simulation_source": "Vault audit log replay", "evidence_expected": "secret read burst event"},
    {"id": "F-014", "phase": 3, "simulation_source": "HR/helpdesk mock + AD admin action log", "evidence_expected": "reset/unlock burst event"},
    {"id": "F-015", "phase": 1, "simulation_source": "RDP/WinRM synthetic session log + Zeek flow", "evidence_expected": "hop-chain session event"},
    {"id": "F-016", "phase": 2, "simulation_source": "Postfix/Dovecot/Roundcube logs", "evidence_expected": "mail volume and attachment-size event"},
    {"id": "F-017", "phase": 2, "simulation_source": "Dovecot/Roundcube rule-change synthetic log", "evidence_expected": "forward/delegate rule change"},
    {"id": "F-018", "phase": 2, "simulation_source": "Dovecot IMAP audit replay", "evidence_expected": "out-of-mailbox access event"},
    {"id": "F-019", "phase": 2, "simulation_source": "Postfix attachment metadata generator", "evidence_expected": "entropy/type mismatch event"},
    {"id": "F-020", "phase": 2, "simulation_source": "Postfix envelope log generator", "evidence_expected": "BCC/distribution-list anomaly"},
    {"id": "F-021", "phase": 2, "simulation_source": "Postfix outbound log + personal-domain sink", "evidence_expected": "personal email attachment event"},
    {"id": "F-022", "phase": 2, "simulation_source": "Postfix outbound log + external-domain allowlist mock", "evidence_expected": "unknown competitor-domain attachment"},
    {"id": "F-023", "phase": 2, "simulation_source": "Mail content metadata generator", "evidence_expected": "sensitive keyword mail event"},
    {"id": "F-024", "phase": 2, "simulation_source": "Dovecot IMAP audit replay", "evidence_expected": "old archive bulk-read event"},
    {"id": "F-025", "phase": 2, "simulation_source": "Roundcube/contact-export synthetic log", "evidence_expected": "address-book export event"},
    {"id": "F-026", "phase": 2, "simulation_source": "Mail text fixture generator", "evidence_expected": "writing-style deviation fixture"},
    {"id": "F-027", "phase": 2, "simulation_source": "Mail text fixture generator", "evidence_expected": "banned phrase policy event"},
    {"id": "F-028", "phase": 2, "simulation_source": "Postfix outbound log + recipient-history fixture", "evidence_expected": "first-time external sensitive mail"},
    {"id": "F-029", "phase": 2, "simulation_source": "Roundcube auth log replay", "evidence_expected": "personal/unknown account login attempt"},
    {"id": "F-030", "phase": 3, "simulation_source": "AI gateway mock + proxy sink", "evidence_expected": "confidential prompt/upload event"},
    {"id": "F-031", "phase": 3, "simulation_source": "AI gateway prompt fixture", "evidence_expected": "source-code/architecture paste event"},
    {"id": "F-032", "phase": 3, "simulation_source": "AI gateway prompt fixture", "evidence_expected": "internal host/user/network prompt event"},
    {"id": "F-033", "phase": 3, "simulation_source": "Proxy sink + unauthorized AI domain list", "evidence_expected": "unapproved AI tool access event"},
    {"id": "F-034", "phase": 3, "simulation_source": "AI gateway upload endpoint mock", "evidence_expected": "AI file upload volume/type event"},
    {"id": "F-035", "phase": 3, "simulation_source": "AI gateway prompt fixture", "evidence_expected": "security-procedure discovery prompt"},
    {"id": "F-036", "phase": 3, "simulation_source": "AI gateway conversation fixture", "evidence_expected": "strategy/legal-content conversation"},
    {"id": "F-037", "phase": 1, "simulation_source": "Samba audit + AD group fixture", "evidence_expected": "out-of-department file access"},
    {"id": "F-038", "phase": 1, "simulation_source": "Samba audit + file operation generator", "evidence_expected": "bulk read/write ratio event"},
    {"id": "F-039", "phase": 1, "simulation_source": "Samba audit + rename storm generator", "evidence_expected": "mass rename rate event"},
    {"id": "F-040", "phase": 1, "simulation_source": "Samba audit + directory traversal replay", "evidence_expected": "sensitive directory traversal event"},
    {"id": "F-041", "phase": 1, "simulation_source": "Samba ACL/change synthetic log", "evidence_expected": "Everyone permission change event"},
    {"id": "F-042", "phase": 3, "simulation_source": "endpoint synthetic generator + local file inventory fixture", "evidence_expected": "local sensitive-data accumulation"},
    {"id": "F-043", "phase": 3, "simulation_source": "file classification mock + Samba/local move log", "evidence_expected": "labeled file moved to unrestricted area"},
    {"id": "F-044", "phase": 3, "simulation_source": "wiki/intranet mock access log", "evidence_expected": "bulk intranet/wiki download"},
    {"id": "F-045", "phase": 2, "simulation_source": "PostgreSQL pg_audit + query replay", "evidence_expected": "bulk table/select scope event"},
    {"id": "F-046", "phase": 2, "simulation_source": "endpoint process tree generator", "evidence_expected": "unusual process duration/tree event"},
    {"id": "F-047", "phase": 2, "simulation_source": "internal API mock + Nginx access log", "evidence_expected": "API call-pattern deviation"},
    {"id": "F-048", "phase": 2, "simulation_source": "Nginx access/error log replay", "evidence_expected": "HTTP 401/403/4xx spike"},
    {"id": "F-049", "phase": 2, "simulation_source": "Gitea + artifact registry mock logs", "evidence_expected": "repo clone/artifact download volume"},
    {"id": "F-050", "phase": 2, "simulation_source": "SIEM/admin console mock audit log", "evidence_expected": "log suppress rule change"},
    {"id": "F-051", "phase": 2, "simulation_source": "hypervisor console mock audit log", "evidence_expected": "management-console access event"},
    {"id": "F-052", "phase": 2, "simulation_source": "endpoint scheduled-task/service synthetic log", "evidence_expected": "new scheduled task/service event"},
    {"id": "F-053", "phase": 2, "simulation_source": "backup/shadow-copy synthetic log", "evidence_expected": "backup disable/delete event"},
    {"id": "F-054", "phase": 2, "simulation_source": "endpoint command-line synthetic log", "evidence_expected": "encoded/policy-bypass script event"},
    {"id": "F-055", "phase": 1, "simulation_source": "endpoint USB generator + file write replay", "evidence_expected": "USB attach/write correlation"},
    {"id": "F-056", "phase": 3, "simulation_source": "CUPS print log + file classification fixture", "evidence_expected": "sensitive print-volume event"},
    {"id": "F-057", "phase": 1, "simulation_source": "endpoint network-state generator", "evidence_expected": "promiscuous mode change event"},
    {"id": "F-058", "phase": 3, "simulation_source": "DLP agent health mock", "evidence_expected": "DLP disable/bypass event"},
    {"id": "F-059", "phase": 3, "simulation_source": "clipboard synthetic generator", "evidence_expected": "large clipboard copy event"},
    {"id": "F-060", "phase": 3, "simulation_source": "screenshot synthetic generator", "evidence_expected": "screenshot frequency spike"},
    {"id": "F-061", "phase": 3, "simulation_source": "AD role seed + flow/session generator", "evidence_expected": "role-to-server contact map deviation"},
    {"id": "F-062", "phase": 3, "simulation_source": "SIEM/log-search mock audit log", "evidence_expected": "risky internal log search keyword"},
    {"id": "F-063", "phase": 1, "simulation_source": "AD login + device inventory fixture", "evidence_expected": "unknown hardware login attempt"},
    {"id": "F-064", "phase": 3, "simulation_source": "user activity generator", "evidence_expected": "compressed activity burst event"},
    {"id": "F-065", "phase": 3, "simulation_source": "app/file access generator + history fixture", "evidence_expected": "dormant system sudden access"},
    {"id": "F-066", "phase": 3, "simulation_source": "peer group baseline fixture + event generator", "evidence_expected": "peer group statistical deviation"},
    {"id": "F-067", "phase": 3, "simulation_source": "cloud/object-storage mock + proxy sink", "evidence_expected": "personal cloud large upload"},
    {"id": "F-068", "phase": 3, "simulation_source": "proxy sink + first-seen destination fixture", "evidence_expected": "first external high-volume transfer"},
    {"id": "F-069", "phase": 3, "simulation_source": "proxy sink + tunnel protocol generator", "evidence_expected": "encrypted tunnel/unusual protocol"},
    {"id": "F-070", "phase": 3, "simulation_source": "Badge API + AD login replay", "evidence_expected": "physical badge/login mismatch"},
    {"id": "F-071", "phase": 3, "simulation_source": "multi-signal event bundle generator", "evidence_expected": "composite risk score input set"},
    {"id": "F-072", "phase": 3, "simulation_source": "HRIS offboarding mock + AD/app activity replay", "evidence_expected": "leaver account activity"},
    {"id": "F-073", "phase": 3, "simulation_source": "Samba/app record access replay", "evidence_expected": "same file/record multi-user chain"},
    {"id": "F-074", "phase": 3, "simulation_source": "Badge API + after-hours login replay", "evidence_expected": "off-shift physical/logical access"},
    {"id": "F-075", "phase": 3, "simulation_source": "HRIS new-hire seed + access replay", "evidence_expected": "new employee excessive access"},
    {"id": "F-076", "phase": 3, "simulation_source": "HRIS role-change seed + old-permission replay", "evidence_expected": "old entitlement use after role change"},
    {"id": "F-077", "phase": 3, "simulation_source": "HRIS leave calendar + activity replay", "evidence_expected": "activity while officially on leave"},
    {"id": "F-078", "phase": 3, "simulation_source": "contractor identity seed + app access replay", "evidence_expected": "contractor out-of-scope system use"},
    {"id": "F-079", "phase": 1, "simulation_source": "AD interactive login replay + work-hours calendar", "evidence_expected": "after-hours interactive session"},
    {"id": "F-080", "phase": 1, "simulation_source": "session log + keyboard/mouse generator", "evidence_expected": "idle session abuse event"},
    {"id": "F-081", "phase": 1, "simulation_source": "role work-window fixture + activity replay", "evidence_expected": "role-based work-window deviation"},
]

FEATURE_TITLES: dict[str, str] = {
    "F-001": "Kullanıcı Başına SMB/Dosya Sunucu Veri Çekim Profili",
    "F-002": "East-West Lateral Trafik Patterni",
    "F-003": "İç DNS Sorgu Entropisi",
    "F-004": "İç Ağda SMB/NTLM Sürüm Düşürme (Downgrade)",
    "F-005": "DHCP/ARP Anomalisi (Rogue DHCP)",
    "F-006": "Başarısız Login Patlaması Sonrası Başarılı Erişim",
    "F-007": "İç Ağ Port Taraması ve Servis Keşfi",
    "F-008": "Kerberos / NTLM Auth Hacmi ve Hedef Çeşitliliği",
    "F-009": "Eşzamanlı Oturum ve Bina İçi Lokasyon Çakışması",
    "F-010": "Hizmet Hesaplarının İnteraktif Kullanımı",
    "F-011": "AD Grup Üyeliği ve Privileged Değişiklik",
    "F-012": "Servis Hesabı ve API Key Kullanım Haritası",
    "F-013": "Secret Store Okuma Burst",
    "F-014": "Credential Reset ve Unlock Yoğunluğu",
    "F-015": "RDP/PSRemoting Hop Pattern",
    "F-016": "Dahili Mail Gönderim Hacmi ve Ek Boyutu",
    "F-017": "Mail Forward/Delegate Kural Değişimi",
    "F-018": "Dahili Mail Kutu Dışı Erişim",
    "F-019": "Mail Ek Entropi ve Dosya Tipi Uyuşmazlığı",
    "F-020": "Gizli Alıcı (BCC) ve Toplu Dağıtım Sapması",
    "F-021": "Kişisel E-posta Adreslerine Ekli Posta Gönderimi",
    "F-022": "Bilinmeyen veya Rakip Kuruluşa Ekli Posta Gönderimi",
    "F-023": "Mail İçeriğinde Hassas Anahtar Kelime Sinyali",
    "F-024": "Eski Mail Arşivinin Toplu Okunması",
    "F-025": "Kişi Listesi veya Adres Defteri Dışa Aktarımı",
    "F-026": "Yazışma Üslubu ve Dil Tonu Sapması",
    "F-027": "Yasaklı veya Politika Dışı İfade Kullanımı",
    "F-028": "İlk Kez Yazışılan Harici Alıcıya Hassas Konulu Mail",
    "F-029": "Kurumsal Mail Sistemine Kişisel/Bilinmeyen Hesapla Giriş Denemesi",
    "F-030": "Harici Yapay Zeka Platformlarına Gizli Veri Gönderimi",
    "F-031": "Kaynak Kod veya Sistem Mimarisi İçeriğinin AI Sohbetine Yapıştırılması",
    "F-032": "AI Prompt İçinde İç Sistem, Kullanıcı veya Ağ Bilgisi Geçmesi",
    "F-033": "Onaylanmamış AI Araçlarının Kurumsal Ağdan Kullanımı",
    "F-034": "AI Platformlarına Dosya Yükleme Hacmi ve İçerik Türü",
    "F-035": "AI ile Şirket Süreçleri ve Güvenlik Prosedürü Keşfi",
    "F-036": "AI Konuşma Geçmişinde Rekabet, Strateji veya Hukuki Süreç İçeriği",
    "F-037": "Departman Dışı Dosya Paylaşım Erişimi",
    "F-038": "Dosya Sunucu Toplu Okuma/Yazma Oranı",
    "F-039": "Kitlesel Dosya Yeniden Adlandırma Hızı",
    "F-040": "Hassas Dizin Dolaşma (Directory Traversal) Davranışı",
    "F-041": "ACL ve Everyone İzin Değişikliği",
    "F-042": "Yerel Diskte Hassas Veri Birikimi",
    "F-043": "Etiketli Hassas Dosyanın Kısıtsız Alana Taşınması",
    "F-044": "Bilgi Bankası/Wiki/Intranet Toplu İndirme",
    "F-045": "Veritabanı Sorgu Hacmi ve Tablo Kapsamı",
    "F-046": "Uygulama Süresi ve Süreç Ağacı",
    "F-047": "İç API Çağrı Deseni Sapması",
    "F-048": "HTTP 4xx Hata Yoğunlaşması",
    "F-049": "Git/Artifact Erişim ve Clone Hacmi",
    "F-050": "SIEM/Log Suppress Kural Değişimi",
    "F-051": "Hypervisor ve Yönetim Konsolu Erişimi",
    "F-052": "Yeni Zamanlanmış Görev veya Sistem Servisi Oluşturulması",
    "F-053": "Yedekleme Gölge Kopyalarının Silinmesi veya Devre Dışı Bırakılması",
    "F-054": "Kodlanmış veya Politika Atlatan Betik Komutları",
    "F-055": "USB Takma-Yazma Korelasyonu",
    "F-056": "Yazıcı İş Hacmi ve Hassas Belge Korelasyonu",
    "F-057": "Ağ Kartı Promiscuous Mod Değişimi",
    "F-058": "DLP Agent Sağlık ve Bypass Denemesi",
    "F-059": "Clipboard Büyük Veri Kopyalama",
    "F-060": "Ekran Görüntüsü Alma Frekansı",
    "F-061": "Rol Bazlı Sunucu Temas Haritası",
    "F-062": "İç Log Arama Anahtar Kelimesi Riski",
    "F-063": "Daha Önce Görülmemiş Donanım Kimliğiyle Oturum Denemesi",
    "F-064": "Normal Aktivite Örüntüsünün Saatler İçinde Yoğunlaşması",
    "F-065": "Uzun Süre Kullanılmayan Sistemlere Ani Erişim",
    "F-066": "Akran Grup Davranışından İstatistiksel Sapma",
    "F-067": "Kişisel Bulut Depolama Hizmetlerine Büyük Dosya Yükleme",
    "F-068": "İlk Kez Görülen Harici Adrese Yüksek Hacimli Veri Transferi",
    "F-069": "Proxy Üzerinden Şifreli Tünel veya Alışılmadık Protokol Kullanımı",
    "F-070": "Fiziksel Badge Geçişi ile Sistem Login Uyuşmazlığı",
    "F-071": "Çapraz Kaynak Risk Skoru (Composite Risk Score)",
    "F-072": "Offboarding SLA — Ayrılan Hesap Aktivitesi",
    "F-073": "Aynı Dosya/Kayıt Çoklu Kullanıcı Erişim Zinciri",
    "F-074": "Vardiya Dışı Fiziksel + Mantıksal Erişim Korelasyonu",
    "F-075": "Yeni Çalışanın İlk Günlerde Aşırı Sistem Erişimi",
    "F-076": "Rol Değişikliği Sonrası Eski Yetkilerin Kullanılması",
    "F-077": "Resmi İzin Kaydı Varken Sistem Aktivitesi",
    "F-078": "Üçüncü Taraf/Yüklenici Kapsam Dışı Sistem Kullanımı",
    "F-079": "Mesai Dışı İnteraktif Oturum",
    "F-080": "Oturum Süresi vs Klavye/Fare Aktivitesi (Boş Oturum Suistimali)",
    "F-081": "Rol Bazlı Aktif Çalışma Penceresi Sapması",
}

FEATURE_CATEGORIES: dict[str, str] = {
    "F-001": "ağ trafiği", "F-002": "ağ trafiği", "F-003": "ağ trafiği",
    "F-004": "ağ trafiği", "F-005": "ağ trafiği", "F-006": "ağ trafiği",
    "F-007": "ağ trafiği", "F-008": "kimlik ve erişim", "F-009": "kimlik ve erişim",
    "F-010": "kimlik ve erişim", "F-011": "kimlik ve erişim", "F-012": "kimlik ve erişim",
    "F-013": "kimlik ve erişim", "F-014": "kimlik ve erişim", "F-015": "kimlik ve erişim",
    "F-016": "mail ve iletişim", "F-017": "mail ve iletişim", "F-018": "mail ve iletişim",
    "F-019": "mail ve iletişim", "F-020": "mail ve iletişim", "F-021": "mail ve iletişim",
    "F-022": "mail ve iletişim", "F-023": "mail ve iletişim", "F-024": "mail ve iletişim",
    "F-025": "mail ve iletişim", "F-026": "mail ve iletişim", "F-027": "mail ve iletişim",
    "F-028": "mail ve iletişim", "F-029": "mail ve iletişim",
    "F-030": "yapay zeka kullanımı", "F-031": "yapay zeka kullanımı", "F-032": "yapay zeka kullanımı",
    "F-033": "yapay zeka kullanımı", "F-034": "yapay zeka kullanımı", "F-035": "yapay zeka kullanımı",
    "F-036": "yapay zeka kullanımı",
    "F-037": "dosya sistemi", "F-038": "dosya sistemi", "F-039": "dosya sistemi",
    "F-040": "dosya sistemi", "F-041": "dosya sistemi", "F-042": "dosya sistemi",
    "F-043": "dosya sistemi", "F-044": "dosya sistemi",
    "F-045": "uygulama ve süreç", "F-046": "uygulama ve süreç", "F-047": "uygulama ve süreç",
    "F-048": "uygulama ve süreç", "F-049": "uygulama ve süreç", "F-050": "uygulama ve süreç",
    "F-051": "uygulama ve süreç", "F-052": "uygulama ve süreç", "F-053": "uygulama ve süreç",
    "F-054": "uygulama ve süreç",
    "F-055": "donanım ve uç nokta", "F-056": "donanım ve uç nokta", "F-057": "donanım ve uç nokta",
    "F-058": "donanım ve uç nokta",
    "F-059": "davranışsal", "F-060": "davranışsal", "F-061": "davranışsal", "F-062": "davranışsal",
    "F-063": "davranışsal", "F-064": "davranışsal", "F-065": "davranışsal", "F-066": "davranışsal",
    "F-067": "dış bağlantı ve çıkış trafiği", "F-068": "dış bağlantı ve çıkış trafiği",
    "F-069": "dış bağlantı ve çıkış trafiği",
    "F-070": "çapraz veri ve korelasyon", "F-071": "çapraz veri ve korelasyon",
    "F-072": "çapraz veri ve korelasyon", "F-073": "çapraz veri ve korelasyon",
    "F-074": "çapraz veri ve korelasyon",
    "F-075": "insan kaynakları ve personel yaşam döngüsü",
    "F-076": "insan kaynakları ve personel yaşam döngüsü",
    "F-077": "insan kaynakları ve personel yaşam döngüsü",
    "F-078": "insan kaynakları ve personel yaşam döngüsü",
    "F-079": "zamanlama", "F-080": "zamanlama", "F-081": "zamanlama",
}

# scenario_id -> feature_ids (primary detection signals per scenario)
SCENARIO_FEATURE_MAP: dict[str, list[str]] = {
    "S-001": ["F-001", "F-079", "F-038", "F-056", "F-081"],
    "S-002": ["F-001", "F-079", "F-038", "F-081"],
    "S-003": ["F-038", "F-039", "F-072", "F-022", "F-068"],
    "S-004": ["F-055", "F-001", "F-042", "F-067"],
    "S-005": ["F-037", "F-039", "F-062", "F-030", "F-036"],
    "S-006": ["F-049", "F-042"],
    "S-007": ["F-045", "F-043", "F-031", "F-034"],
    "S-008": ["F-001", "F-055", "F-053", "F-067", "F-068"],
    "S-009": ["F-045", "F-066"],
    "S-010": ["F-038", "F-037"],
    "S-011": ["F-024", "F-025", "F-019"],
    "S-012": ["F-047", "F-075"],
    "S-013": ["F-038", "F-018", "F-060"],
    "S-014": ["F-051", "F-001", "F-055"],
    "S-015": ["F-045"],
    "S-016": ["F-008", "F-015", "F-079"],
    "S-017": ["F-013"],
    "S-018": ["F-079", "F-010", "F-015"],
    "S-019": ["F-010"],
    "S-020": ["F-009", "F-070"],
    "S-021": ["F-012", "F-047"],
    "S-022": ["F-010", "F-012", "F-047"],
    "S-023": ["F-079", "F-063", "F-070"],
    "S-024": ["F-012"],
    "S-025": ["F-015", "F-063"],
    "S-026": ["F-009"],
    "S-027": ["F-017"],
    "S-028": ["F-015", "F-061", "F-079"],
    "S-029": ["F-037", "F-040"],
    "S-030": ["F-011"],
    "S-031": ["F-042", "F-054"],
    "S-032": ["F-045", "F-065"],
    "S-033": ["F-015", "F-048"],
    "S-034": ["F-011"],
    "S-035": ["F-007"],
    "S-036": ["F-018", "F-024"],
    "S-037": ["F-037"],
    "S-038": ["F-048"],
    "S-039": ["F-051", "F-050"],
    "S-040": ["F-011", "F-052"],
    "S-041": ["F-047"],
    "S-042": ["F-050", "F-058"],
    "S-043": ["F-053"],
    "S-044": ["F-062", "F-054", "F-058"],
    "S-045": ["F-024", "F-018"],
    "S-046": ["F-075"],
    "S-047": ["F-001", "F-072", "F-064"],
    "S-048": ["F-047"],
    "S-049": ["F-062"],
    "S-050": ["F-066", "F-072"],
    "S-051": ["F-041"],
    "S-052": ["F-020", "F-023"],
    "S-053": ["F-006", "F-048"],
    "S-054": ["F-045", "F-048", "F-007"],
    "S-055": ["F-055", "F-043"],
    "S-056": ["F-080", "F-037"],
    "S-057": ["F-043", "F-038"],
    "S-058": ["F-055", "F-063"],
    "S-059": ["F-049", "F-042", "F-054"],
    "S-060": ["F-037", "F-038"],
    "S-061": ["F-014"],
    "S-062": ["F-049", "F-054"],
    "S-063": ["F-014"],
    "S-064": ["F-057"],
    "S-065": ["F-078", "F-072"],
    "S-066": ["F-041", "F-039"],
    "S-067": ["F-006", "F-070", "F-074"],
    "S-068": ["F-007"],
    "S-069": ["F-003", "F-005"],
    "S-070": ["F-054", "F-008"],
    "S-071": ["F-006", "F-048"],
    "S-072": ["F-002", "F-057"],
    "S-073": ["F-046", "F-059"],
    "S-074": ["F-046", "F-065"],
    "S-075": ["F-037", "F-063", "F-079"],
    "S-076": ["F-011", "F-014"],
    "S-077": ["F-023", "F-026"],
    "S-078": ["F-048", "F-006"],
    "S-079": ["F-016", "F-020", "F-023"],
    "S-080": ["F-071", "F-044", "F-012", "F-050", "F-038"],
    "S-081": ["F-071", "F-074", "F-015", "F-062"],
    "S-082": ["F-014", "F-072", "F-024"],
    "S-083": ["F-073", "F-039", "F-037"],
}

SCENARIOS: list[dict] = [
    {"id": "S-001", "title": "Gece Yarısı Finans Paylaşımı", "category": "veri sızdırma", "user_role": "CFO", "severity": "CRITICAL", "seed": 1001},
    {"id": "S-002", "title": "Gece Yedek Çekimi", "category": "veri sızdırma", "user_role": "Muhasebe", "severity": "CRITICAL", "seed": 1002},
    {"id": "S-003", "title": "Satış Ekibinden Sessiz CRM Dökümü", "category": "veri sızdırma", "user_role": "Satış", "severity": "CRITICAL", "seed": 1003},
    {"id": "S-004", "title": "IT Admin Fazladan USB Yedekleme", "category": "veri sızdırma", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 1004},
    {"id": "S-005", "title": "CTO'nun Gizli Yedek Klasörü", "category": "veri sızdırma", "user_role": "CTO", "severity": "CRITICAL", "seed": 1005},
    {"id": "S-006", "title": "Kaynak Kod Deposunun Kitlesel Klonlanması", "category": "veri sızdırma", "user_role": "Yazılım Geliştirici", "severity": "CRITICAL", "seed": 1006},
    {"id": "S-007", "title": "Geçici Toplantı Dosyasında Gizlenen Veritabanı Dökümü", "category": "veri sızdırma", "user_role": "Yazılım Geliştirici", "severity": "CRITICAL", "seed": 1007},
    {"id": "S-008", "title": "Yedekleme Sunucusundan Olağan Dışı Veri Çekme", "category": "veri sızdırma", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 1008},
    {"id": "S-009", "title": "BI Ham PII Export", "category": "veri sızdırma", "user_role": "Veri Analisti", "severity": "ALERT", "seed": 1009},
    {"id": "S-010", "title": "İK'dan Toplu CV Arşivi Kopyası", "category": "veri sızdırma", "user_role": "İK", "severity": "ALERT", "seed": 1010},
    {"id": "S-011", "title": "CEO Mail Kutusundan Toplu Arşiv Export", "category": "veri sızdırma", "user_role": "CEO", "severity": "CRITICAL", "seed": 1011},
    {"id": "S-012", "title": "Stajyer CRM Export", "category": "veri sızdırma", "user_role": "Stajyer", "severity": "CRITICAL", "seed": 1012},
    {"id": "S-013", "title": "Destek Ticket PII Toplu Arşivi", "category": "veri sızdırma", "user_role": "Destek Personeli", "severity": "ALERT", "seed": 1013},
    {"id": "S-014", "title": "Admin Prod-HR VM Snapshot", "category": "veri sızdırma", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 1014},
    {"id": "S-015", "title": "Payroll SQL Dump", "category": "veri sızdırma", "user_role": "İK", "severity": "CRITICAL", "seed": 1015},
    {"id": "S-016", "title": "Gece Admin Kerberos TGT Zinciri", "category": "credential ihlali", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 2016},
    {"id": "S-017", "title": "Token Vault Dump", "category": "credential ihlali", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 2017},
    {"id": "S-018", "title": "Domain Admin Hesabıyla Sıra Dışı Giriş", "category": "credential ihlali", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 2018},
    {"id": "S-019", "title": "Hizmet Hesabının Kötüye Kullanımı", "category": "credential ihlali", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 2019},
    {"id": "S-020", "title": "Çoklu Lokasyon Çakışması", "category": "credential ihlali", "user_role": "CEO", "severity": "CRITICAL", "seed": 2020},
    {"id": "S-021", "title": "Eski Credential ile API Kullanımı", "category": "credential ihlali", "user_role": "Yazılım Geliştirici", "severity": "CRITICAL", "seed": 2021},
    {"id": "S-022", "title": "API Servis Hesabını İnsan Gibi Kullanan Analist", "category": "credential ihlali", "user_role": "Veri Analisti", "severity": "ALERT", "seed": 2022},
    {"id": "S-023", "title": "Muhasebe Terminalinden Gece Loginleri", "category": "credential ihlali", "user_role": "Muhasebe", "severity": "CRITICAL", "seed": 2023},
    {"id": "S-024", "title": "Deploy Key 3 Farklı IP", "category": "credential ihlali", "user_role": "Yazılım Geliştirici", "severity": "ALERT", "seed": 2024},
    {"id": "S-025", "title": "Admin Hesaplarının Çapraz Kullanımı", "category": "credential ihlali", "user_role": "IT Admin", "severity": "ALERT", "seed": 2025},
    {"id": "S-026", "title": "Stajyer Çift Oturum", "category": "credential ihlali", "user_role": "Stajyer", "severity": "ALERT", "seed": 2026},
    {"id": "S-027", "title": "İç Ağda Gizli Posta Kuralı Oluşturma", "category": "credential ihlali", "user_role": "Satış", "severity": "ALERT", "seed": 2027},
    {"id": "S-028", "title": "IT Admin Yetki Zinciri", "category": "yetkisiz erişim", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 3028},
    {"id": "S-029", "title": "Hukuk Belgelerine Meraklı Geliştirici", "category": "yetkisiz erişim", "user_role": "Yazılım Geliştirici", "severity": "CRITICAL", "seed": 3029},
    {"id": "S-030", "title": "Yetki Yükseltme (Privilege Escalation)", "category": "yetkisiz erişim", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 3030},
    {"id": "S-031", "title": "CTO Bilgisayarından SSH Anahtarı Hasadı", "category": "yetkisiz erişim", "user_role": "CTO", "severity": "CRITICAL", "seed": 3031},
    {"id": "S-032", "title": "Junior Dev Prod Veritabanı Erişimi", "category": "yetkisiz erişim", "user_role": "Yazılım Geliştirici", "severity": "CRITICAL", "seed": 3032},
    {"id": "S-033", "title": "Destek Personeli DC RDP", "category": "yetkisiz erişim", "user_role": "Destek Personeli", "severity": "CRITICAL", "seed": 3033},
    {"id": "S-034", "title": "Muhasebe Domain Admin Grubu Denemesi", "category": "yetkisiz erişim", "user_role": "Muhasebe", "severity": "CRITICAL", "seed": 3034},
    {"id": "S-035", "title": "Stajyer Ağ Keşfi", "category": "yetkisiz erişim", "user_role": "Stajyer", "severity": "ALERT", "seed": 3035},
    {"id": "S-036", "title": "Veri Analistinin Tüm Posta Kutusu Taraması", "category": "yetkisiz erişim", "user_role": "Veri Analisti", "severity": "ALERT", "seed": 3036},
    {"id": "S-037", "title": "Satıştan Muhasebeye Kesişen Erişim", "category": "yetkisiz erişim", "user_role": "Satış", "severity": "ALERT", "seed": 3037},
    {"id": "S-038", "title": "Güvenlik Duvarı Kurallarının Esnetilmesi", "category": "yetkisiz erişim", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 3038},
    {"id": "S-039", "title": "PM SIEM Konsol Erişimi", "category": "yetkisiz erişim", "user_role": "Proje Yöneticisi", "severity": "ALERT", "seed": 3039},
    {"id": "S-040", "title": "Shadow Admin Hesabı Oluşturma", "category": "insider threat", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 4040},
    {"id": "S-041", "title": "Sahte Tedarikçi IBAN Değişikliği", "category": "insider threat", "user_role": "Muhasebe", "severity": "CRITICAL", "seed": 4041},
    {"id": "S-042", "title": "SOC Log Suppress Kuralı", "category": "insider threat", "user_role": "Güvenlik Görevlisi", "severity": "CRITICAL", "seed": 4042},
    {"id": "S-043", "title": "Admin Tarafından Eski Yedeklerin Silinmesi", "category": "insider threat", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 4043},
    {"id": "S-044", "title": "Yönetici Yetkisiyle Kitlesel Log Silme", "category": "insider threat", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 4044},
    {"id": "S-045", "title": "İK Hesabından Gece Mail Arşiv Taraması", "category": "insider threat", "user_role": "İK", "severity": "CRITICAL", "seed": 4045},
    {"id": "S-046", "title": "İK Sisteminde Hayalet Çalışan Oluşturma", "category": "insider threat", "user_role": "İK", "severity": "CRITICAL", "seed": 4046},
    {"id": "S-047", "title": "Ayrılış Öncesi Veri Rampa-Up", "category": "insider threat", "user_role": "Yazılım Geliştirici", "severity": "ALERT", "seed": 4047},
    {"id": "S-048", "title": "PM Proje Maliyet Tablosu Toplu Güncelleme", "category": "insider threat", "user_role": "Proje Yöneticisi", "severity": "ALERT", "seed": 4048},
    {"id": "S-049", "title": "Muhasebe Login Saatleri Toplu İnceleme", "category": "insider threat", "user_role": "Muhasebe", "severity": "ALERT", "seed": 4049},
    {"id": "S-050", "title": "Satış Müşteri Segmentasyon Modeline Erişim", "category": "insider threat", "user_role": "Satış", "severity": "ALERT", "seed": 4050},
    {"id": "S-051", "title": "Yanlış Paylaşılan Bordro Klasörü", "category": "kazara ihlal", "user_role": "Muhasebe", "severity": "ALERT", "seed": 5051},
    {"id": "S-052", "title": "İK'dan Yanlış Odaya Giden Hassas Mail", "category": "kazara ihlal", "user_role": "İK", "severity": "WARNING", "seed": 5052},
    {"id": "S-053", "title": "Yeni Yazılımcının Hatalı Script Döngüsü", "category": "kazara ihlal", "user_role": "Yazılım Geliştirici", "severity": "ALERT", "seed": 5053},
    {"id": "S-054", "title": "Canlı Ortam Yerine Test Aracı Yanlışlığı", "category": "kazara ihlal", "user_role": "Yazılım Geliştirici", "severity": "ALERT", "seed": 5054},
    {"id": "S-055", "title": "USB ile İçeri Veri Taşıyan Stajyer", "category": "kazara ihlal", "user_role": "Stajyer", "severity": "ALERT", "seed": 5055},
    {"id": "S-056", "title": "Destek Personelinin Aşırı Geniş Oturum Süresi", "category": "kazara ihlal", "user_role": "Destek Personeli", "severity": "WARNING", "seed": 5056},
    {"id": "S-057", "title": "Veri Analistinin Legal Hold Dosyalarını Dahil Etmesi", "category": "kazara ihlal", "user_role": "Veri Analisti", "severity": "ALERT", "seed": 5057},
    {"id": "S-058", "title": "Hukuk Bilgisayarına Bilinmeyen USB Takılması", "category": "kazara ihlal", "user_role": "Hukuk", "severity": "ALERT", "seed": 5058},
    {"id": "S-059", "title": "Stajyerin Kaynak Kod Aynası", "category": "politika ihlali", "user_role": "Stajyer", "severity": "ALERT", "seed": 6059},
    {"id": "S-060", "title": "Hukuk Klasörünü Yedekleyen PM", "category": "politika ihlali", "user_role": "Proje Yöneticisi", "severity": "ALERT", "seed": 6060},
    {"id": "S-061", "title": "PM'den Gereksiz Credential İstemi", "category": "politika ihlali", "user_role": "Proje Yöneticisi", "severity": "ALERT", "seed": 6061},
    {"id": "S-062", "title": "Sabit Şifre Koda Gömme", "category": "politika ihlali", "user_role": "Yazılım Geliştirici", "severity": "ALERT", "seed": 6062},
    {"id": "S-063", "title": "Süresi Dolan Şifrelerin Toplu Uzatılması", "category": "politika ihlali", "user_role": "IT Admin", "severity": "WARNING", "seed": 6063},
    {"id": "S-064", "title": "Stajyerin Wi-Fi Ağı Sniffing Denemesi", "category": "politika ihlali", "user_role": "Stajyer", "severity": "CRITICAL", "seed": 6064},
    {"id": "S-065", "title": "Geçici Erişim Süresinin Aşılması", "category": "politika ihlali", "user_role": "IT Admin", "severity": "WARNING", "seed": 6065},
    {"id": "S-066", "title": "Hukuk Toplu PDF OCR Geçici Klasörü", "category": "politika ihlali", "user_role": "Hukuk", "severity": "ALERT", "seed": 6066},
    {"id": "S-067", "title": "Güvenlik Görevlisinin Sunucu Odası Erişim Olayı", "category": "dış saldırı desteği", "user_role": "Güvenlik Görevlisi", "severity": "CRITICAL", "seed": 7067},
    {"id": "S-068", "title": "Admin Bilgisayarından Agresif Port Taraması", "category": "dış saldırı desteği", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 7068},
    {"id": "S-069", "title": "DNS Sunucu Yönlendirme Manipülasyonu", "category": "dış saldırı desteği", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 7069},
    {"id": "S-070", "title": "Domain Controller Üzerinde Credential Dumping Script", "category": "dış saldırı desteği", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 7070},
    {"id": "S-071", "title": "Geliştirici Bilgisayarından SSH Kaba Kuvvet Saldırısı", "category": "dış saldırı desteği", "user_role": "Yazılım Geliştirici", "severity": "CRITICAL", "seed": 7071},
    {"id": "S-072", "title": "CTO Hesabından Ağ Trafik Kopyalama Kuralı", "category": "dış saldırı desteği", "user_role": "CTO", "severity": "CRITICAL", "seed": 7072},
    {"id": "S-073", "title": "İK Bilgisayarında Keylogger Çalışması", "category": "dış saldırı desteği", "user_role": "İK", "severity": "CRITICAL", "seed": 7073},
    {"id": "S-074", "title": "Docker Container Escape Denemesi", "category": "dış saldırı desteği", "user_role": "Yazılım Geliştirici", "severity": "CRITICAL", "seed": 7074},
    {"id": "S-075", "title": "CEO Asistanı Gibi Davranan Arama Sonrası Erişim", "category": "sosyal mühendislik", "user_role": "CEO", "severity": "ALERT", "seed": 8075},
    {"id": "S-076", "title": "CFO'dan Gelen Acil Onay Talebi Sonrası Yetki Verme", "category": "sosyal mühendislik", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 8076},
    {"id": "S-077", "title": "Hukuk Ekibine CFO Adına Gelen Sahte İç Mail", "category": "sosyal mühendislik", "user_role": "Hukuk", "severity": "ALERT", "seed": 8077},
    {"id": "S-078", "title": "Sosyal Mühendislik Tuzağına Düşen Yeni Başlayan", "category": "sosyal mühendislik", "user_role": "Destek Personeli", "severity": "ALERT", "seed": 8078},
    {"id": "S-079", "title": "Tüm Şirkete Sahte CEO İstifa Maili", "category": "sosyal mühendislik", "user_role": "İK", "severity": "CRITICAL", "seed": 8079},
    {"id": "S-080", "title": "Çok Kaynaklı Kademeli İhlal Simülasyonu", "category": "çapraz/multi-user", "user_role": "IT Admin", "severity": "CRITICAL", "seed": 9080},
    {"id": "S-081", "title": "Çoklu Departman Zincirli Fiziksel-Dijital Saldırı", "category": "çapraz/multi-user", "user_role": "Güvenlik Görevlisi", "severity": "CRITICAL", "seed": 9081},
    {"id": "S-082", "title": "İK ve Bilgi İşlem Çapraz Hesap Manipülasyonu", "category": "çapraz/multi-user", "user_role": "İK", "severity": "CRITICAL", "seed": 9082},
    {"id": "S-083", "title": "Aynı Dosyaya Zincirleme Çapraz Departman Erişimi", "category": "çapraz/multi-user", "user_role": "Satış", "severity": "ALERT", "seed": 9083},
]
